# Round-9 fix plan data: lanes (groups), PRs, findings, dependencies.
# Consumed by gen.py. Paths are relative to the repo root; CC is the package.
CC = "custom_components/heatpump_optimizer/"
EV = "79aa98ec"  # evidence commit that carries tools/audit/round9/ harnesses

# ---------------------------------------------------------------- lanes
# Each lane is one cloud fixer thread. OWNS lists the files only that lane may
# open a branch on. Shared ledgers (EXEMPT) follow the class-named sorted-block
# rule of PLAN section 9.4 instead of ownership.
EXEMPT = [
    "tests/features.py", "tests/entities.py", "tests/closures.json",
    "tests/structure_budgets.json", "tests/seam_map.json",
    "tests/golden/claimed_drift.txt", "tests/golden/card_claimed_drift.txt",
    "docs/delivery/<N>.md",
]

LANES = {
 "F1": dict(name="Coordinator cycle, state and clock", model="opus", topic="r9-f1-coordinator",
   owns=[CC+"coordinator.py", CC+"services.py", CC+"store.py", CC+"button.py", CC+"manual_plan.py",
         CC+"accuracy.py", CC+"external_heat.py", CC+"dhw_learning.py",
         "tests/dst_checks.py", "tests/open_meteo.py"]),
 "F2": dict(name="Solver and plant model", model="opus", topic="r9-f2-solver",
   owns=[CC+"optimizer.py", CC+"pv.py", CC+"thermal_model.py"]),
 "F3": dict(name="Persisted stores and price/weather feeds", model="opus", topic="r9-f3-stores",
   owns=[CC+"snapshots.py", CC+"curve_learning.py", CC+"comfort_learning.py", CC+"pump_arbiter.py",
         CC+"freq_control.py", CC+"defrost.py", CC+"legionella.py", CC+"boost.py", CC+"away.py",
         CC+"drift.py", CC+"disinfection.py", CC+"price_model.py", CC+"tariff.py", CC+"open_meteo.py",
         CC+"grid_fee.py", CC+"dhw_draws.py", CC+"ledger.py"]),
 "F4": dict(name="Inputs, constants, sysid and flow-lift", model="opus", topic="r9-f4-inputs-sysid",
   owns=[CC+"inputs.py", CC+"const.py", CC+"sysid.py", CC+"flow_lift.py", CC+"currency.py"]),
 "F5": dict(name="Config flow and translated text", model="sonnet", topic="r9-f5-config-text",
   owns=[CC+"config_flow.py", CC+"strings.json", CC+"translations/en.json", CC+"translations/sv.json",
         CC+"icons.json", CC+"quality_scale.yaml", CC+"quick_setup.py", CC+"modbus_prefill.py",
         CC+"topology.py", "tests/config_flow_steps.py"]),
 "F6": dict(name="Dashboard card", model="opus", topic="r9-f6-card",
   owns=[CC+"www/heatpump-optimizer-card.js", "tests/card.mjs", "tests/card_rig.mjs",
         "tests/card_drift.mjs", "tests/card_browser.mjs"]),
 "F7": dict(name="Entities", model="opus", topic="r9-f7-entities",
   owns=[CC+"sensor.py", CC+"climate.py", CC+"switch.py", CC+"entity.py", CC+"binary_sensor.py"]),
 "F8": dict(name="User documentation", model="sonnet", topic="r9-f8-docs",
   owns=["README.md", "docs/configuration.md", "docs/setup.md", "docs/how-it-works.md",
         "docs/dashboard-card.md", "docs/ecl110.md"]),
 "F9": dict(name="Test pins for unpinned guards", model="sonnet", topic="r9-f9-test-pins",
   owns=["tests/finite_boundary.py", "tests/nightly_ha.py"]),
 "F10": dict(name="Gate, stub and ratchet infrastructure", model="opus", topic="r9-f10-gate-infra",
   owns=["tests/hastub/**", "tests/ha_contract.py", "tests/replay.py", "tests/stress.py",
         "tests/stress_budgets.json", "tests/env_drift.py", "tests/closure.py", "tests/derive_closures.sh",
         "tests/deployment_shape.py", "tests/doc_claims.py", "tests/mutation_table.py",
         "tests/mutation_budgets.json", "tests/structure.py", "tests/harness.py"]),
 "F11": dict(name="Governance tooling and policy", model="opus", topic="r9-f11-governance",
   owns=[".claude/workflows/**", ".github/**", "CLAUDE.md", "AGENTS.md", ".claude/rules/**",
         ".cursor/rules/**", ".claude/settings.json", "tools/audit/**", "tools/release/**",
         "docs/decisions/**"]),
}

# ---------------------------------------------------------------- classes
CLASS_SHORT = {
 "avoidable interpreter-bound recomputation in the solve": "N-solve-recompute",
 "CPU gate blind to a regression outside its sampled work": "N-cpu-gate-blind",
 "user state not surviving restart": "N-restart",
 "CPU work inline on the event loop": "N-loop-cpu",
 "live input with no physical-plausibility bound": "N-plausibility",
 "persisted future instant trusted without bound": "N-future-instant",
 "production member reached by no production code": "N-dead-member",
 "a sign floor on a price margin breaks the stated piecewise identity": "N-sign-floor",
 "an approval bound to an exact head is re-bought on a diff-identical move": "N-approval-rebuy",
 "an entity family whose names do not lead with a shared token splits under the name sort": "N-name-sort",
 "compatibility duplicate entity enabled by default": "N-dup-entity",
 "error-translating try opened after the call it should cover": "N-late-try",
 "explicit-Euler stability judged per store instead of on the coupled step matrix": "N-euler-coupled",
 "fit integrator differs from the simulated plant": "N-fit-integrator",
 "learned-correction clamp sized against an assumed range, not the model's curve": "N-clamp-range",
 "markdown the renderer misplaces": "N-markdown",
 "missing icons.json services block": "N-service-icons",
 "persistent failure swallowed at DEBUG": "N-debug-swallow",
 "pointer-only editing with no keyboard route": "N-keyboard",
 "return inside finally": "N-finally-return",
 "selector minimum off its own step grid": "N-step-grid",
 "series resolution inferred from the minimum gap": "N-min-gap",
 "service input without an upper-bound clamp": "N-service-clamp",
 "shutdown reap waits on the lock a solve holds": "N-reap-lock",
 "solve-scoped mutation of shared live config seen by a concurrent reader": "N-shared-config",
 "staleness limit shorter than a report-on-change sensor's quiet interval": "N-staleness",
 "state-blind menu re-offers a completed path": "N-menu",
 "structure metric blind to a code shape": "N-structure-blind",
 "text producer takes no language parameter": "N-language",
 "translation leaf double-escaped": "N-escape",
 "whole-entity availability gated on an optional input": "N-availability",
}
SWEEP_OF = {"P2": "S1", "I5": "S2", "I1": "S3", "P1": "S3", "I3": "S4", "P11": "S4", "I4": "S4", "P6": "S4",
            "P9": "S5", "N-solve-recompute": "S5", "P3": "S5", "P5": "S5", "N-cpu-gate-blind": "S5",
            "N-restart": "S5"}
S7 = {"N-loop-cpu", "N-future-instant", "I2", "P7", "N-approval-rebuy", "N-dup-entity", "N-euler-coupled",
      "N-clamp-range", "N-service-icons", "N-keyboard", "N-step-grid", "N-service-clamp", "N-shared-config",
      "N-menu", "N-language", "N-availability"}

# RCA seats (strongest model), the PR they sit beside first, and where the barrier lands.
# `note` is the sweep's barrier proposal in one line; the RCA seat names the form (root-cause.md).
RCA = {
 "P2": dict(beside="F3.1", barrier="F1.10", note="S1 proposes one lint generalising the P2 enumerator: a registry of canonical predicates, and every other decision context reading the same key or threshold refused; sub-shape checks may ride instance PRs (F1.2's proxy-key check), the class-level check lands last"),
 "I5": dict(beside="F8.1", barrier="F10.4", note="S2 finds no single production seam (8 claim shapes); proposes a nightly lane running the shape-checkers, failing on any false/mismatch count; the seat sizes it and chooses nightly or per-PR"),
 "I1": dict(beside="F9.1", barrier="F10.3", note="S3 proposes two: widen the mutation inventory's candidates (D14-s5-02) and a closure-scoped non-UTC lane for tzinfo and timestamp seams (D3-s1-91, D3-s3-01, D7-s1-02)"),
 "P1": dict(beside="F3.1", barrier="F1.6", note="S3 proposes one validated-load helper (convert, isfinite, clamp) used by every loader, about 15 call sites; the store-fuzz check goes in tests/finite_boundary.py"),
 "I3": dict(beside="F11.1", barrier="F11.3", note="S4 proposes the hooks check reading each hook's matcher, and a per-file byte or token cap beside the line cap (or a zero band on the pooled aggregates); owner-gated"),
 "P11": dict(beside="F10.1", barrier="F10.3", note="S4 proposes tests/ha_contract.py contracts for each divergent stub, run nightly against the real package, including the currency and Tibber-reauth probes"),
 "I4": dict(beside="F11.1", barrier="F11.4", note="S4 proposes one shared frontmatter-paths parser, the GOV pin deriving its watched workflows from governance.yml, and one class-id module for the 31 readers"),
 "P6": dict(beside="F1.2", barrier="F1.10", note="S4 proposes one generated producer/consumer key manifest in tests/entities.py, promoting the p6_keys census"),
 "P9": dict(beside="F6.1", barrier="F6.3", note="S5 proposes the enumerate.mjs canonical grid as a browser lane asserting zero contrast, popup-out, indistinct-option, now-marker and label-overlap instances"),
 "N-solve-recompute": dict(beside="F2.2", barrier="F10.2", note="S5 proposes a nightly call-count ratchet (recompute instances may only fall); the seat may prefer a structural form or a CPU budget the stress gate sees"),
 "P3": dict(beside="F2.1", barrier="F1.10", note="S5 proposes the p3_floors enumerator as a lint refusing a new floor group or a floor above the schema minimum"),
 "P5": dict(beside="F4.2", barrier="F4.2", note="S5 proposes the p5_gate sweep as a tests/ script asserting zero admitted-over-bar cells"),
 "N-cpu-gate-blind": dict(beside="F10.2", barrier="F10.2", note="S5 proposes three additive stress/replay channels: non-kernel solve CPU, a loop-thread cost channel, a throttling-valve scenario"),
 "N-restart": dict(beside="F1.4", barrier="F1.4", note="barriered class (RC2): S5 proposes the two enumerators (store race, params restart) as regressions asserting lost == 0, extending the RC2 barrier"),
 "N-future-instant": dict(beside="F3.1", barrier="F1.9", note="new at Phase D (S7 raised N past 3): an AST lint over every fromisoformat reachable from a persisted-store load that reaches a now comparison with no clamp at the restore site"),
}

# ---------------------------------------------------------------- Phase D sweeps
# Each sweep thread's output commit (branch handoff/audit-r9-sweep-s<n>) and, per
# plan class, the directory under tools/audit/round9/D14/sweep/ and its enumerator.
SWEEP_COMMIT = {"S1": "c44e7bcd60", "S2": "38f1230e92", "S3": "053c4869ad", "S4": "b2e3560671",
                "S5": "51a2e98a86", "S6": "6b65c9c4a8", "S7": "1152a74346"}
# sweep JSON class label -> plan class id (labels the plan already uses map to themselves)
SWEEP_LABEL = {
 "avoidable interpreter-bound recomputation in the solve": "N-solve-recompute",
 "CPU gate blind to a regression outside its sampled work": "N-cpu-gate-blind",
 "user state not surviving restart": "N-restart",
 "live-input-no-plausibility-bound": "N-plausibility",
 "production-member-no-caller": "N-dead-member",
 "sign-floor-price-margin": "N-sign-floor",
 "entity-family-name-sort-split": "N-name-sort",
 "error-translating-try-after-call": "N-late-try",
 "fit-integrator-differs-from-plant": "N-fit-integrator",
 "markdown-renderer-misplaces": "N-markdown",
 "persistent-failure-debug-swallow": "N-debug-swallow",
 "return-inside-finally": "N-finally-return",
 "series-resolution-min-gap": "N-min-gap",
 "shutdown-reap-lock-held": "N-reap-lock",
 "staleness-limit-shorter-than-quiet-interval": "N-staleness",
 "structure-metric-blind-to-shape": "N-structure-blind",
 "translation-leaf-double-escaped": "N-escape",
}
SWEEP_DIR = {
 "N-solve-recompute": ("avoidable-interpreter-bound-recomputation", "enumerate.py"),
 "N-cpu-gate-blind": ("cpu-gate-blind", "enumerate_nonkernel.py"),
 "N-restart": ("user-state-not-surviving-restart", "enumerate_store_race.py"),
 "N-plausibility": ("live-input-no-plausibility-bound", "enumerate.sh"),
 "N-dead-member": ("production-member-no-caller", "enumerate.sh"),
 "N-sign-floor": ("sign-floor-price-margin", "enumerate.sh"),
 "N-name-sort": ("entity-family-name-sort-split", "enumerate.sh"),
 "N-late-try": ("error-translating-try-after-call", "enumerate.sh"),
 "N-fit-integrator": ("fit-integrator-differs-from-plant", "enumerate.sh"),
 "N-markdown": ("markdown-renderer-misplaces", "enumerate.sh"),
 "N-debug-swallow": ("persistent-failure-debug-swallow", "enumerate.sh"),
 "N-finally-return": ("return-inside-finally", "enumerate.py"),
 "N-min-gap": ("series-resolution-min-gap", "enumerate.sh"),
 "N-reap-lock": ("shutdown-reap-lock-held", "enumerate.sh"),
 "N-staleness": ("staleness-limit-shorter-than-quiet-interval", "enumerate.sh"),
 "N-structure-blind": ("structure-metric-blind-to-shape", "enumerate.sh"),
 "N-escape": ("translation-leaf-double-escaped", "enumerate.sh"),
 "N-loop-cpu": ("cpu_work_inline_event_loop", "enumerate.py"),
 "N-future-instant": ("persisted_future_instant_unbounded", "enumerate.py"),
 "N-approval-rebuy": ("approval_bound_exact_head", "yield_rounds.mjs"),
 "N-dup-entity": ("compat_duplicate_entity", "enumerate.py"),
 "N-euler-coupled": ("euler_stability_per_store", "SWEEP.md"),
 "N-clamp-range": ("learned_clamp_assumed_range", "SWEEP.md"),
 "N-service-icons": ("missing_icons_services", "enumerate.py"),
 "N-keyboard": ("pointer_only_no_keyboard", "enumerate.py"),
 "N-step-grid": ("selector_min_off_step_grid", "enumerate.py"),
 "N-service-clamp": ("service_input_no_upper_clamp", "SWEEP.md"),
 "N-shared-config": ("solve_scoped_mutation_shared_config", "SWEEP.md"),
 "N-menu": ("state_blind_menu_reoffer", "SWEEP.md"),
 "N-language": ("text_producer_no_language", "SWEEP.md"),
 "N-availability": ("whole_entity_avail_optional_input", "SWEEP.md"),
 "P2": ("P2", "enumerator.py"), "I5": ("I5", "enumerator.py"), "I1": ("I1", "enumerator.py"),
 "P1": ("P1", "enumerator.py"), "I3": ("I3", "enumerate.py"), "P11": ("P11", "enumerate.py"),
 "I4": ("I4", "enumerate.py"), "P6": ("P6", "enumerate.py"), "P9": ("P9", "enumerate.mjs"),
 "P3": ("P3", "enumerate.py"), "P5": ("P5", "enumerate.py"), "P8": ("P8", "enumerate.sh"),
 "P4": ("P4", "enumerate.sh"), "I2": ("I2", "closure_divergence.py"), "P7": ("P7", "p7_static_sites.py"),
}

# Sweep-confirmed instances beyond the judged findings (N final = judged + these).
# Each joins a PR; `pr` is where its failing test (the sweep probe) and fix land.
# Line numbers are at baseline 1936d5ca; re-anchor at your merge base.
INSTANCES = [
 dict(id="P1-sw1", cls="P1", pr="F1.6", file=CC+"comfort_learning.py",
      seam="ComfortLearner.from_dict, the stored_configured leaf (baseline line 236)",
      what="a NaN stored_configured passes the stale-weight gate instead of being discarded by it",
      probe="tools/audit/round9/D14/sweep/P1/probes.py"),
 dict(id="P1-sw2", cls="P1", pr="F1.6", file=CC+"comfort_learning.py",
      seam="ComfortLearner.from_dict, the learned_weight and evidence leaves (baseline lines 244-245)",
      what="a float() cast with no isfinite check",
      probe="tools/audit/round9/D14/sweep/P1/probes.py"),
 dict(id="P9-sw1", cls="P9", pr="F6.1", file=CC+"www/heatpump-optimizer-card.js",
      seam="the chart's SVG axis number and unit label pairs",
      what="the unit suffix sits at a fixed offset from its number with no measured-width check, so the pair overlaps at 1280 and 375 px wide (the enumerator's overlap_instances, distinct from D4-s1-05's now-marker collisions)",
      probe="tools/audit/round9/D14/sweep/P9/enumerate.mjs"),
 dict(id="RC-sw1", cls="N-solve-recompute", pr="F2.2", file=CC+"optimizer.py",
      seam="cycling_penalty_batch",
      what="the same per-row Python loop as D9-s1-01's, in an independent function called once per iterate",
      probe="tools/audit/round9/D14/sweep/avoidable-interpreter-bound-recomputation/enumerate.py"),
 dict(id="FI-sw1", cls="N-future-instant", pr="F1.9", file=CC+"coordinator.py",
      seam="the fuse advisor's 7-day recompute cooldown (_fuse_advisor_at restored from the ledger store; baseline lines 8007 and 8023-8024)",
      what="a restored instant written ahead of the clock holds the cooldown active indefinitely",
      probe="tools/audit/round9/D14/sweep/persisted_future_instant_unbounded/probe_fuse_advisor.py"),
 dict(id="FI-sw2", cls="N-future-instant", pr="F1.9", file=CC+"coordinator.py",
      seam="the heavy-snow damping window (_last_heavy_snow restored from the store; baseline lines 2953 and 6306)",
      what="damping stays on while the restored instant is ahead of now",
      probe="tools/audit/round9/D14/sweep/persisted_future_instant_unbounded/probe_more_instances.py"),
 dict(id="FI-sw3", cls="N-future-instant", pr="F1.9", file=CC+"coordinator.py",
      seam="_detect_outage's staggered-recovery window (the stored last_tick; baseline lines 7343 and 8099-8114)",
      what="a future last_tick masks a real outage",
      probe="tools/audit/round9/D14/sweep/persisted_future_instant_unbounded/probe_more_instances.py"),
 dict(id="FI-sw4", cls="N-future-instant", pr="F1.9", file=CC+"coordinator.py",
      seam="the immersion-event recency count (_immersion_events; baseline line 8381)",
      what="same shape, lower confidence: not separately probed, and it needs three or more corrupted entries to move the output; probe it first and disposition it with the measurement if it does not reproduce",
      probe="none (S7 disposed it on the mechanism)"),
 dict(id="FI-sw5", cls="N-future-instant", pr="F3.2", file=CC+"pump_arbiter.py",
      seam="hold()'s write-echo grace period (held.written restored in _load; baseline lines 629 and 405-407)",
      what="a restored write instant ahead of the clock keeps the grace period open",
      probe="tools/audit/round9/D14/sweep/persisted_future_instant_unbounded/probe_more_instances.py"),
]

# Sweep output that is not an instance and joins no PR as one, placed as a note.
LEADS = [
 ("P9 keyboard route (S5, exposure, not counted)", "F6.2",
  "S5 ran its grid with the keyboard cells off, so the 204 pointer-only hits across 8 selectors (both chart pan surfaces, the six setup-picker entity rows) are unverified for a keyboard route. S7's pointer-only sweep disposed the chart pan as guarded (zoom buttons) and the picker surface as guarded (its own keydown handler); D4-s1-04's fixer re-checks the six setup-hit rows with the keyboard cells on and dispositions each."),
 ("P5 lead: async_update_thermal_params has no gate (S5)", "F1.4",
  "The set_thermal_parameters service writes house_heat_loss_scale and buffer_cooling_rate with no admission gate. S5 disposed it not applicable to P5 (no gate to key wrong), so it is not a P5 instance and not counted; it is D1-s2-53's seam. D1-s2-53's fixer decides, with the measurement, whether the service write is bounded like the sysid adoption, and says so; F4.2's P5 barrier does not cover this writer."),
]

# Ledger notes (not RCA triggers this round), recorded in FIX-PLAN.md only.
LEDGER_NOTES = [
 "P4 (S6): the ledger's most recurring class, 14 historical instances in rounds 1-7, never barriered or given a detector; N=1 this round (D0-s2-02, F2.4), so no RCA seat. Flagged for whoever owns the ledger's cross-round view.",
 "P7 (S7): recurred in 4 of 6 swept rounds (2, 3, 5, 9) with no barrier; N=1 this round (D14-s4-01). F1.1's DST tracer barrier is D14-s4-01's own fix, not a class barrier.",
 "I2 (S7): recurred in 5 of 6 swept rounds (2, 3, 5, 7, 9) with no barrier; N=1 this round (D14-s5-01, F10.3).",
 "S4: the per-file policy-doc cap counts lines, with no byte or token guard. That is D11-s2-01 (F11.3), whose seams S4 widened to every capped file; no new PR.",
]

# ---------------------------------------------------------------- PRs
# findings: list of (id, part) where part is None (whole finding) or a string naming the part.
PRS = [
 # ---------------- F1 coordinator
 dict(id="F1.1", lane="F1", title="DST wall-clock seams and the gate's clock",
   findings=[("D14-s4-01", "coordinator, accuracy, dhw_learning and external_heat seams, plus the DST tracer barrier"),
             ("D14-s4-02", None), ("D3-s1-91", None), ("D3-s3-01", None)],
   edit=[CC+"coordinator.py", CC+"accuracy.py", CC+"dhw_learning.py", CC+"external_heat.py",
         "tests/dst_checks.py", "tests/open_meteo.py"],
   borrows={"tests/replay.py": "F10"}, after=["F2.1"], tvofi=None,
   notes=["Route every duration through `_utc_age_seconds` (or `dt_util.as_utc` on both sides) and every forward instant through UTC; `_forecast_arrays` step_offset is the high seam.",
          "Verifier carry-in (G3-V2): `run_fixture` in tests/replay.py must also step its clock in UTC, not only convert `_ts`; otherwise part of the DST day stays blind.",
          "tests/dst_checks.py gains a post-transition clock; D3-s1-91's guards in coordinator.py are exercised under an aware clock and must not crash when unblinded.",
          "D3-s3-01 is closed in tests/open_meteo.py by running its driver under a non-UTC process zone; do not edit tests/run.sh (code-owned).",
          "The optimizer seam of D14-s4-01 (`get_current_action` step length) lands first in F2.1; the tracer barrier here must read zero only after it."]),
 dict(id="F1.2", lane="F1", title="Presence inferred from untouched defaults; DHW start state",
   findings=[("D12-s1-01", None), ("D12-s3-01", None), ("D14-s2-01", None)],
   edit=[CC+"coordinator.py"], borrows={CC+"config_flow.py": "F5", CC+"modbus_prefill.py": "F5", CC+"topology.py": "F5"},
   after=["F1.1"], tvofi=None,
   notes=["Fix-together sibling (DEDUP): D12-s1-01 lands in one PR with D12-s1-02, which the judge merged into D12-s3-01 (with D4-s2-04).",
          "D12-s1-01: when the tank probe gives no ok reading, seed the next solve's DHW state from the previous plan's trajectory at the elapsed step instead of the ThermalState default.",
          "D12-s3-01: write explicit presence (hot water, two zones) from the answers the way `quick_setup` derives it, so untouched form defaults stop acting as presence; L2 extra seam: config_flow `async_step_dhw`.",
          "D14-s2-01: route the three proxy-key seams through the canonical predicates (`_dhw_enabled_from_config` and the two-zone predicate); its tests/entities.py check is the P2 sub-barrier for this shape.",
          "Borrows config_flow.py, modbus_prefill.py and topology.py from F5: F5.2 does not open until this PR merges."]),
 dict(id="F1.3", lane="F1", title="Cycle outcome: stale spot price, unfenced cycle calls, failures reported as success",
   findings=[("D2-s3-01", None), ("D1-s2-51", None), ("D1-s2-91", None), ("D1-s4-02", None), ("D10-s1-02", None)],
   edit=[CC+"coordinator.py", CC+"button.py"], borrows={}, after=["F1.2"], tvofi=None,
   notes=["D2-s3-01 (merged D8-s1-01): `_current_spot_price` covers [start, next start) the way `_known_prices_for` does; the settlement and comfort learner share the reader.",
          "D1-s2-51 and D1-s2-91 (fix together): fence each learner and arbiter call on the cycle path; the judge narrowed D1-s2-51 to the arbiter half, and D1-s2-91's `_record_accuracy` seams are in scope.",
          "D1-s4-02: the coordinator's failure branch treats a result whose status starts 'failed' as a failed solve; keep optimizer.py untouched (owned by F2).",
          "D10-s1-02: the optimize-now button raises when the solve did not run, like the run_optimization action; re-check button.py against #1641 and #1643, merged after the baseline."]),
 dict(id="F1.4", lane="F1", title="Restart durability (barriered class) and store bounds",
   findings=[("D1-s2-52", None), ("D1-s2-53", None), ("D1-s2-54", None), ("D1-s2-03", None)],
   edit=[CC+"coordinator.py", CC+"store.py", CC+"services.py", CC+"manual_plan.py"], borrows={}, after=["F1.3"], tvofi=None,
   notes=["Barriered class (RC2, merged as #1641 after the baseline): re-measure D1-s2-52 and D1-s2-53 against origin/main first; an instance that survives extends the RC2 barrier in the same PR.",
          "D1-s2-54 (merged D6-s1-04): clamp expires_at to MANUAL_PLAN_WINDOW_HOURS, which makes README's statement true; no README edit.",
          "D1-s2-03: reject non-finite or out-of-range sample counts when `_async_load_thermal_learning` parses the store."]),
 dict(id="F1.5", lane="F1", title="Cycle failures: swallowed errors, late try, reap, P6 defaults, defrost fold",
   findings=[("D1-s2-04", None), ("D1-s2-55", None), ("D1-s2-05", None), ("D2-s1-51", None), ("D7-s2-02", None)],
   edit=[CC+"coordinator.py"], borrows={}, after=["F1.4"], tvofi=None,
   notes=["D1-s2-55: open the try before `_ensure_worker` so a spawn OSError reaches the in-process fallback and its repair notice.",
          "D1-s2-05: `_shutdown_process_pool` takes the worker handle without waiting on `_PROCESS_LOCK` (kill first, keep the lock only for the swap).",
          "D1-s2-04: first occurrence of each swallowed cause at WARNING, repeats at DEBUG, as the worker-fallback note already does.",
          "D7-s2-02: skip the inferred defrost fallback fold when `_cop_fold_blocked` refuses.",
          "D2-s1-51: the DHW setpoint advisor must not price at the ThermalState outdoor default when no outdoor reading exists."]),
 dict(id="F1.6", lane="F1", title="Plausibility bounds and the P1 load-layer barrier",
   findings=[("D1-s2-02", None), ("D1-s1-03", None), ("D14-s1-01", None)],
   edit=[CC+"coordinator.py", CC+"dhw_learning.py", CC+"manual_plan.py"],
   borrows={CC+"legionella.py": "F3", CC+"boost.py": "F3", CC+"pump_arbiter.py": "F3", CC+"snapshots.py": "F3",
            CC+"away.py": "F3", CC+"comfort_learning.py": "F3", CC+"inputs.py": "F4", "tests/finite_boundary.py": "F9"},
   after=["F1.5", "F3.3", "F4.1", "F9.1"], tvofi=None,
   notes=["D1-s2-02 and D1-s1-03 reuse the plausibility window F4.1 adds to inputs.py for D1-s5-52 (one class, three boundaries: DEDUP).",
          "D14-s1-01 is the P1 class detector: its fix is the barrier, one shared stored-instant and leaf parser used at every store read it lists, extending the helper F3.1 introduced; `_maybe_run_fuse_advisor` and `_apply_learner_payloads` are the coordinator seams.",
          "The P1 RCA seat names the barrier's form; the store-fuzz check goes in tests/finite_boundary.py after F9.1 merges.",
          "The two P1 sweep instances (P1-sw1, P1-sw2) are ComfortLearner.from_dict leaves, borrowed from F3 because the P1 barrier's load helper closes them: they travel with the barrier rather than opening a fourth F3 PR. The P1 enumerator must read zero instance seams at this PR's head."]),
 dict(id="F1.7", lane="F1", title="Coordinator readers across lanes: loop CPU, auth, settlement scale",
   findings=[("D9-s1-03", None), ("D9-s2-01", None), ("D10-s1-03", None), ("D2-s2-01", None)],
   edit=[CC+"coordinator.py"],
   borrows={CC+"sysid.py": "F4", CC+"sensor.py": "F7", CC+"topology.py": "F5", CC+"optimizer.py": "F2",
            "tests/hastub/homeassistant/exceptions.py": "F10", "tests/hastub/homeassistant/helpers/update_coordinator.py": "F10"},
   after=["F1.6", "F2.4", "F4.2", "F5.2", "F10.1"], tvofi=None,
   notes=["D9-s1-03: the sysid fit runs off the loop (executor job the coordinator awaits); `step` only marks the experiment finished.",
          "D9-s2-01: compute the sensor-advisor ranking once per cycle in the coordinator; both plan sensors read the cached value.",
          "D10-s1-03: raise ConfigEntryAuthFailed on the reauth verdict through both update wrappers; the stub gains the exception after F10.1.",
          "D2-s2-01: apply `house_heat_loss_scale` in `slab_settlement_cap` and `hold_demand_kw` (optimizer.py) and at the coordinator seams the verifier found (`_space_demand_kw` and the battery-view consumer)."]),
 dict(id="F1.8", lane="F1", title="Currency and unit (P8) and entry identity",
   findings=[("D14-s2-02", None), ("D12-s3-81", None), ("D10-s1-01", None)],
   edit=[CC+"coordinator.py", CC+"services.py"],
   borrows={CC+"inputs.py": "F4", CC+"currency.py": "F4", CC+"config_flow.py": "F5", CC+"strings.json": "F5",
            CC+"translations/en.json": "F5", CC+"translations/sv.json": "F5", "tests/config_flow_steps.py": "F5",
            CC+"www/heatpump-optimizer-card.js": "F6", CC+"grid_fee.py": "F3", CC+"price_model.py": "F3"},
   after=["F1.7", "F5.2", "F6.2", "F3.3"], tvofi=None,
   notes=["D14-s2-02 (merged D4-s2-02): keep the price feed's declared money code beside the label currency and raise a repair issue on disagreement; the firewood price widget through `resolve_currency`; one card resolver for money units.",
          "D12-s3-81: grid-fee bounds scale with the currency instead of SEK literals (`IMPLAUSIBLE_FEE_SEK_PER_KWH`).",
          "P8's sweep (S6) lists eight instance seams for these two findings, one in price_model.py (the price unit parsed and its money code discarded), which is why this PR borrows price_model.py from F3.",
          "D10-s1-01: re-derive the entry unique id in `async_step_reauth_confirm` and the options save; verifier carry-in (G2-V3): services.py `handle_assign_entity` is a seam too."]),
 dict(id="F1.9", lane="F1", title="Persisted future instants in the coordinator; the class barrier",
   findings=[], edit=[CC+"coordinator.py"], borrows={}, after=["F1.8", "F3.2"], tvofi=None,
   notes=["A class Phase D created: S7 widened 'persisted future instant trusted without bound' from the judge's two findings (D1-s1-04, D1-s3-05, both in F3.1) to seven, so it owes a barrier (defect-root-cause.md). Its four coordinator instances travel with the barrier here; the pump-arbiter instance (FI-sw5) lands in F3.2, which owns that file.",
          "Fix: clamp each restored instant to the moment it is read back, at the restore site, through the stored-instant parser F3.1 introduces and F1.6 extends; do not add a second parser. The probes (probe_fuse_advisor.py, probe_more_instances.py) are the failing tests: each positive arm must read as its clamped perturbation arm reads today (for three instances the window stays stuck at day 30; for _detect_outage the outage is masked), with every null arm unchanged.",
          "Barrier (the RCA seat names the form): S7 proposes an AST lint over every fromisoformat call reachable from a persisted-store load that reaches a now comparison with no clamp at the restore site, promoted into tests/entities.py as a zero-seam check. It lands only after F3.1 and F3.2, and is shown failing on each of the seven instances re-introduced, passing on the fixed tree, silent on a healthy tree."]),
 dict(id="F1.10", lane="F1", title="Class barriers P2, P3, P6; comment drift; boost test hook",
   findings=[("D14-s3-01", None), ("D14-s1-02", None), ("D5-s2-02", None)],
   edit=[CC+"coordinator.py"],
   borrows={CC+"sensor.py": "F7", CC+"boost.py": "F3", CC+"defrost.py": "F3", CC+"tariff.py": "F3", CC+"away.py": "F3",
            CC+"const.py": "F4", CC+"sysid.py": "F4", CC+"optimizer.py": "F2", CC+"thermal_model.py": "F2",
            "tests/harness.py": "F10"},
   after=["F1.8", "F2.4", "F6.4"], tvofi="tests/harness.py is code-owned (D14-s1-02 moves the test double's persist patch there)",
   notes=["Lands after every P2, P3 and P6 instance PR: the class-level checks read zero on main only then.",
          "D14-s3-01: the floor-group enumerator becomes a check that refuses a new floor group or a floor raised above the quantity's schema minimum.",
          "D14-s1-02: publish horizon_hours or drop the read; remove the boost test hook from `boost.set_channel`; the P6 barrier is the p6_keys arms at zero.",
          "D5-s2-02: three comments whose numbers the code does not deliver (defrost.py, const.py, coordinator.py)."]),
 # ---------------- F2 solver
 dict(id="F2.1", lane="F2", title="get_current_action seams, two-zone comfort floor, PV margin, stale comments",
   findings=[("D14-s4-01", "optimizer seam: get_current_action step length"), ("D12-s2-03", None), ("D2-s2-81", None),
             ("D2-s3-02", None), ("D5-s2-51", None)],
   edit=[CC+"optimizer.py", CC+"pv.py"], borrows={}, after=[], tvofi=None,
   notes=["First in F2 and short: F1.1 waits on the DST seam in `get_current_action`.",
          "D12-s2-03: `get_current_action` handles a zero modulation range (on/off pump is off or at full) and clamps the normalised power.",
          "D2-s2-81: the two-zone comfort penalty must not halve each zone's floor price.",
          "D2-s3-02: drop the zero clip in `import_margin` (or guard only non-finite) and correct its docstring."]),
 dict(id="F2.2", lane="F2", title="Interpreter-bound recomputation in the solve",
   findings=[("D9-s1-01", None), ("D9-s1-02", None), ("D9-s1-04", None), ("D9-s1-71", None)],
   edit=[CC+"optimizer.py", CC+"thermal_model.py"], borrows={}, after=["F2.1"], tvofi=None,
   notes=["Bitwise parity is per architecture (fixer.md step 15): run the scalar expression per row, drive the parity grid at the production width.",
          "Verifier carry-in (G3-V1): the vectorised `_comfort_terms_batch` loses parity on Fortran-order batches; the parity grid must include one.",
          "D9-s1-02: fuse f and g in `_multi_start_minimize` and `_lbfgsb_restart`; D9-s1-04: early exit in `_apply_dhw_min_run`; D9-s1-71: a per-solve cache of the constant DHW parameter helpers.",
          "S5 widened D9-s1-71 to every ThermalParameters property called more than once per step (eleven in its profiled solve, including dhw_hard_max_temp, dhw_windows_active, topology_layout and two_tank_modelled); these are folded into D9-s1-71, not counted, and the two cheap boolean ones are low priority. The one counted new instance (RC-sw1) is cycling_penalty_batch, whose per-row loop takes the same fix as D9-s1-01."]),
 dict(id="F2.3", lane="F2", title="Plant-model physics and the thrice-held inlet default",
   findings=[("D2-s1-01", None), ("D2-s1-02", None), ("D2-s2-03", None), ("D7-s1-71", None), ("D5-s2-03", None)],
   edit=[CC+"thermal_model.py", CC+"optimizer.py"], borrows={CC+"const.py": "F4"}, after=["F2.2", "F4.1"], tvofi=None,
   notes=["D2-s1-01: `_stability_substeps` judges the coupled step matrix, not each store's diagonal.",
          "D2-s1-02: debit the wood tank on the scale the DHW step applies; the optimizer's `dhw_coil_draw_reduction` mirror follows.",
          "D2-s2-03: judge carry-in: cover the baseline_end sibling of `_replay_end_state` too; expect wood_coil golden drift, claimed with direction.",
          "D7-s1-71 and D5-s2-03 (fix together): every site reads DEFAULT_DHW_INLET_TEMP; retire or re-comment DHW_COLD_WATER_TEMP in const.py."]),
 dict(id="F2.4", lane="F2", title="On/off pump threshold at both seams; multi-start seeds",
   findings=[("D12-s2-01", None), ("D8-s1-03", None), ("D0-s2-02", None)],
   edit=[CC+"optimizer.py"],
   borrows={CC+"pump_arbiter.py": "F3", CC+"entity.py": "F7", CC+"sensor.py": "F7", CC+"climate.py": "F7"},
   after=["F2.3", "F1.6", "F7.2", "F5.2"], tvofi=None,
   notes=["Fix-together siblings (DEDUP): D12-s2-01 first, at both seams (`_power_to_heat_pump_schedule` and the arbiter's on-threshold); D8-s1-03 then re-measures, because its 'publish zero when off' alone would hide D12-s2-01.",
          "L2 extra seam for D8-s1-03: climate.py recommended power shares `commanded_power_kw`.",
          "D0-s2-02: a cheaper seed or a recorded refusal priced in money and CPU; the #1294 refusal stands against the anchor ladder. Judge carry-in from refuted D0-s1-01: the two-zone deep-anchor asymmetry between `_optimize_space_only` and `_solve_space` is hygiene to weigh here, not a finding."]),
 # ---------------- F3 stores
 dict(id="F3.1", lane="F3", title="Stored instants: naive and future timestamps",
   findings=[("D1-s3-01", None), ("D1-s1-01", None), ("D1-s1-04", None), ("D1-s3-05", None), ("D1-s1-02", None)],
   edit=[CC+"away.py", CC+"boost.py", CC+"legionella.py", CC+"pump_arbiter.py", CC+"snapshots.py",
         CC+"curve_learning.py", CC+"comfort_learning.py", CC+"drift.py"], borrows={}, after=[], tvofi=None,
   notes=["One shared stored-instant parser (naive becomes aware, a future instant is clamped), used at `_parse_return_time`, `_parse_until`, the legionella and arbiter loaders, snapshots, curve and comfort learners and `Cusum`; F1.6 extends it as the P1 barrier.",
          "D1-s3-01 is high: the card's datetime-local handler (L2 seam) is dispositioned as guarded by the parser, not edited here.",
          "G1-V2 side observation folded into I1's sweep: `boost.restore` raises on a naive stored until under the real HA clock; close it here.",
          "D1-s1-02: guarded float of the stored bias in `best_restore`."]),
 dict(id="F3.2", lane="F3", title="Pump-duty arbiter and the frequency map",
   findings=[("D1-s3-02", None), ("D1-s3-03", None), ("D12-s2-02", None), ("D1-s3-06", None)],
   edit=[CC+"pump_arbiter.py", CC+"freq_control.py"], borrows={}, after=["F3.1"], tvofi=None,
   notes=["D1-s3-02 (weakened, 1 of 31 unload offsets): return early on a released entry and refuse to re-arm listeners.",
          "D12-s2-02: route the mode write by the target's domain (select or input_select); a read-only slot is refused, not written.",
          "D1-s3-06: bound the decile key and the ratio in `FrequencyMap.from_dict`.",
          "FI-sw5 (future-instant class, S7): clamp the restored write instant at the restore site through F3.1's parser; F1.9's class barrier must read it as closed."]),
 dict(id="F3.3", lane="F3", title="Learner stores and feed parsers",
   findings=[("D1-s4-01", None), ("D1-s4-03", None), ("D1-s5-02", None), ("D1-s5-03", None), ("D1-s5-04", None)],
   edit=[CC+"defrost.py", CC+"price_model.py", CC+"tariff.py", CC+"open_meteo.py"], borrows={}, after=["F3.2"], tvofi=None,
   notes=["D1-s4-01 is weakened: `QuarantiningStore` scrubs non-finite leaves, so only the finite out-of-range cells remain in scope.",
          "D1-s5-03 is weakened: only the price-entity seam is reachable (orjson refuses huge integers over HTTP).",
          "D1-s5-02: `PriceShapeModel.from_dict` applies the observe clip ranges; peaks drop negatives like non-finite ones.",
          "D1-s5-04: infer the resolution from the dominant gap in `_parse_block`, not the minimum."]),
 # ---------------- F4 inputs and sysid
 dict(id="F4.1", lane="F4", title="Input freshness and plausibility; flow-lift clamp",
   findings=[("D1-s5-52", None), ("D1-s5-01", None), ("D1-s5-51", None), ("D2-s2-02", None)],
   edit=[CC+"inputs.py", CC+"const.py", CC+"flow_lift.py"], borrows={}, after=[], tvofi=None,
   notes=["Fix-together siblings (DEDUP): D1-s5-01 and D1-s5-51 land in this one PR (`age_of` precedence and the indoor staleness limit).",
          "D1-s5-52 is high: a plausibility window in `InputReader` for every temperature key; F1.6 reuses it for the forecast and DHW-learner boundaries.",
          "D2-s2-02: size `FLOW_BIAS_CLAMP_K` against the model curve's actual range (thermal_model.py is read, not edited)."]),
 dict(id="F4.2", lane="F4", title="System identification: adoption gate, fit integrator, sizing (P5)",
   findings=[("D2-s4-01", None), ("D2-s4-81", None), ("D14-s3-03", None), ("D7-s2-01", None), ("D2-s4-02", None)],
   edit=[CC+"sysid.py"], borrows={}, after=["F4.1"], tvofi=None,
   notes=["P5 fits in one PR: the barrier (p5_gate sweep as a check) rides here.",
          "D2-s4-01 is weakened (inverse crime); the fine-plant fit bias is D7-s2-01: sub-step the candidate rollout independent of the sample interval.",
          "D14-s3-03: coordinator.py is only the caller; the gate lives in `adoption_decision`. If the fix needs coordinator.py, stop and hand the part back to F1."]),
 # ---------------- F5 config flow and text
 dict(id="F5.1", lane="F5", title="Translated text, icons and names (no config_flow.py)",
   findings=[("D4-s2-03", None), ("D4-s2-08", None), ("D4-s2-09", None), ("D8-s3-02", None), ("D8-s3-01", None),
             ("D5-s1-02", "L2 seam: the quick-setup text in en.json and sv.json"), ("D6-s2-03", "L2 seam: the curve-bias figure in strings.json")],
   edit=[CC+"strings.json", CC+"translations/en.json", CC+"translations/sv.json", CC+"icons.json"], borrows={}, after=[], tvofi=None,
   notes=["Does not open config_flow.py, modbus_prefill.py or topology.py: F1.2 borrows them first.",
          "D8-s3-01 is weakened: only the energy-meter family half stands; names only, unique ids untouched.",
          "D4-s2-03: fix the double-escaped leaves; a translation check for backslash-u sequences is the natural pin."]),
 dict(id="F5.2", lane="F5", title="Setup wizard and options UX",
   findings=[("D4-s2-01", None), ("D4-s2-05", None), ("D4-s2-06", None), ("D4-s2-07", None), ("D10-s2-01", None)],
   edit=[CC+"config_flow.py", CC+"strings.json", CC+"translations/en.json", CC+"translations/sv.json", CC+"icons.json",
         CC+"quality_scale.yaml", "tests/config_flow_steps.py"],
   borrows={CC+"climate.py": "F7"}, after=["F5.1", "F1.2", "F7.1"], tvofi=None,
   notes=["D10-s2-01 is weakened: give the climate entity a translation key and translate or map the auto and economy presets; update quality_scale.yaml rows.",
          "D4-s2-06: show the derivation-overwrite warning on every page that renders a DERIVED_THERMAL_KEYS field.",
          "D4-s2-05: minima on their own step grid in `_number` and the range constants."]),
 # ---------------- F6 card
 dict(id="F6.1", lane="F6", title="Card layout, colour and hit targets (P9)",
   findings=[("D4-s1-01", None), ("D4-s1-02", None), ("D4-s1-03", None), ("D4-s1-05", None)],
   edit=[CC+"www/heatpump-optimizer-card.js", "tests/card.mjs", "tests/card_drift.mjs"], borrows={}, after=[], tvofi=None,
   notes=["Pins go in tests/card.mjs or tests/card_drift.mjs; anything that needs tests/card_browser.mjs (code-owned) waits for F6.3.",
          "D4-s1-02 and D4-s1-05 are weakened; re-check the card against #1643 (merged after the baseline) before measuring.",
          "P9-sw1 (S5): place each axis unit label by its number's measured box, as D4-s1-05's fix places the now-temp label; the enumerator's overlap count is the pin for both."]),
 dict(id="F6.2", lane="F6", title="Keyboard route in the layout editor; stale comments; #1643 surviving mutants",
   findings=[("D4-s1-04", None), ("D5-s2-01", None)],
   edit=[CC+"www/heatpump-optimizer-card.js", "tests/card.mjs"], borrows={}, after=["F6.1"], tvofi=None,
   carry=["RESUME carry-in (#1643, merged db878b29): pin its surviving card mutants: ghi as a step mean; overlays() iterating covered; the null-stretch denominator in the step mean; askedThrough."],
   notes=["D4-s1-04: focusable, named pipe and box elements with key handlers (delete, move, connect)."]),
 dict(id="F6.3", lane="F6", title="P9 class barrier in the browser lane",
   findings=[], edit=["tests/card_browser.mjs"], borrows={}, after=["F6.2"],
   tvofi="tests/card_browser.mjs is code-owned",
   notes=["The P9 RCA seat names the barrier; the D14-s4 card sweep (target, clip, contrast) and the contrast lane's status states are the candidates. Demonstrated failing on each round-9 P9 instance re-introduced."]),
 dict(id="F6.4", lane="F6", title="Language-aware setup text; raw-thermometer source for staleness gaps",
   findings=[("D4-s2-81", None)],
   edit=[CC+"www/heatpump-optimizer-card.js"],
   borrows={CC+"topology.py": "F5", CC+"config_flow.py": "F5", CC+"sensor.py": "F7", CC+"strings.json": "F5",
            CC+"translations/en.json": "F5", CC+"translations/sv.json": "F5"},
   after=["F6.3", "F1.8"], tvofi=None,
   carry=["RESUME carry-in (L1 indoor-sensor lead, D4 side): a source-id attribute so the card can draw the raw thermometer through a staleness gap; lands after D1-s5-51's fix (F4.1)."],
   notes=["D4-s2-81: `describe_setup` and the diagram text take the install's language."]),
 # ---------------- F7 entities
 dict(id="F7.1", lane="F7", title="Climate entity: hvac_action during boost, mode reads, away target",
   findings=[("D8-s2-02", None), ("D8-s2-03", None), ("D1-s3-04", None)],
   edit=[CC+"climate.py", CC+"switch.py"], borrows={}, after=[], tvofi=None,
   notes=["Fix-together siblings (DEDUP): D8-s2-02 and D8-s2-03 in one PR; the finder's D8-s2-03 fix would reintroduce D8-s2-02, so key `hvac_action` on the running action, not the mode alone.",
          "D1-s3-04 is weakened (default-off peak-guard path only). Its class sweep (S7) proposes publishing target_temperature from the per-cycle coordinator.data snapshot; if the fix needs coordinator.py or away.py, stop and hand that part to F1 or F3 rather than borrowing."]),
 dict(id="F7.2", lane="F7", title="Sensors: schedule count, duplicate entity, valve recommendation",
   findings=[("D8-s1-02", None), ("D8-s3-03", None), ("D8-s3-61", None)],
   edit=[CC+"sensor.py", CC+"binary_sensor.py"], borrows={"README.md": "F8"}, after=["F7.1", "F8.3"], tvofi=None,
   notes=["README seams: D8-s3-61's row and the L2 seam for D8-s3-03 (the Upper Floor row); README is borrowed after F8.3."]),
 dict(id="F7.3", lane="F7", title="Climate availability without an indoor thermometer (owner's ruling)",
   findings=[("D8-s2-01", None)], edit=[CC+"climate.py"], borrows={}, after=["F7.2", "F2.4"],
   tvofi="the fix overturns the owner's recorded A3(e) decision pinned in tests/entities.py; tvofi rules first",
   notes=["If tvofi keeps A3(e), no PR is opened: the finding is dispositioned refused with the ruling."]),
 # ---------------- F8 docs
 dict(id="F8.1", lane="F8", title="configuration.md: initial setup, entity count, services",
   findings=[("D5-s1-01", None), ("D6-s2-01", None), ("D6-s2-02", None), ("D5-s1-04", None), ("D6-s2-05", None)],
   edit=["docs/configuration.md"], borrows={}, after=[], tvofi=None,
   notes=["DEDUP: D5-s1-01, D6-s2-01 and D6-s2-02 are one rewrite of the Initial setup section; D6-s2-05 carries merged D5-s1-06.",
          "Derive the entity count from the tree at your merge base; never carry the finder's figure."]),
 dict(id="F8.2", lane="F8", title="Labels, pages and solver description",
   findings=[("D5-s1-05", None), ("D6-s1-02", None), ("D6-s2-04", None), ("D6-s1-01", None), ("D6-s1-03", None)],
   edit=["docs/configuration.md", "docs/how-it-works.md", "README.md"], borrows={}, after=["F8.1"], tvofi=None,
   notes=["DEDUP: D5-s1-05 and D6-s1-02 are one doc PR.", "D6-s1-01: derive the state list from HEAT_PUMP_ACTION_STATES."]),
 dict(id="F8.3", lane="F8", title="Setup promises, curve-bias figure, currency fallback, card version",
   findings=[("D5-s1-02", "docs/setup.md"), ("D6-s2-03", "docs"), ("D6-s1-81", None), ("D5-s1-03", None)],
   edit=["docs/setup.md", "docs/ecl110.md", "docs/configuration.md", "docs/how-it-works.md", "README.md", "docs/dashboard-card.md"],
   borrows={}, after=["F8.2", "F5.1"], tvofi=None,
   notes=["D5-s1-02 and D6-s2-03 close here; their translation seams landed in F5.1.",
          "D5-s1-03: docs/dashboard-card.md changed in #1643 after the baseline; re-measure first.",
          "The I5 barrier is not here: I5 has instances in F2.1, F2.3, F6.2, F1.10 and F11.3 (comments and CLAUDE.md), so it lands in F10.4, after all of them."]),
 # ---------------- F9 test pins
 dict(id="F9.1", lane="F9", title="Pins for deletable guards (I1), part 1",
   findings=[("D3-s1-01", None), ("D3-s2-01", None), ("D3-s2-02", None), ("D3-s3-02", None), ("D3-s3-03", None)],
   edit=["tests/finite_boundary.py"], borrows={}, after=[], tvofi=None,
   notes=["Test-only. Mutation proof is the light in-memory mutant check (tvofi): apply the mutant in memory, call the production symbol, show the new pin fails; no pools, pre-screens or quiet window.",
          "D3-s2-01 is weakened: through `QuarantiningStore` only the flow_lift restore guard stays reachable."]),
 dict(id="F9.2", lane="F9", title="Pins for deletable guards (I1), part 2; return inside finally",
   findings=[("D3-s3-04", None), ("D3-s3-05", None), ("D7-s3-51", None)],
   edit=["tests/nightly_ha.py"], borrows={}, after=["F9.1"], tvofi=None,
   notes=["D7-s3-51: `_async_check_a4` must not return inside finally."]),
 # ---------------- F10 gate infra
 dict(id="F10.1", lane="F10", title="Home Assistant stub fidelity (P11) and its contracts",
   findings=[("D1-s1-51", None), ("D1-s1-52", None), ("D1-s2-71", None)],
   edit=["tests/hastub/homeassistant/helpers/storage.py", "tests/hastub/homeassistant/util/dt.py",
         "tests/hastub/homeassistant/helpers/update_coordinator.py", "tests/ha_contract.py"],
   borrows={}, after=[], tvofi=None,
   notes=["D1-s1-52 makes the stub clock aware by default: measure the suite's response at the merge base and the head; claim any golden that moves, with direction; if the ripple exceeds one PR, split it out and say so.",
          "Each stub this PR repairs gains its tests/ha_contract.py contract here (fixer.md step 13). The P11 class barrier is not here: P11 also has instances in F1.1 (the replay clock), F1.7 (Tibber reauth) and F8.3 (the currency fallback), so it lands in F10.3."]),
 dict(id="F10.2", lane="F10", title="CPU gate blind spots; per-solve CPU budget",
   findings=[("D9-s2-02", None), ("D9-s2-03", None), ("D9-s2-71", None)],
   edit=["tests/stress.py", "tests/stress_budgets.json", "tests/replay.py"], borrows={}, after=["F1.1", "F2.2"],
   tvofi="tests/stress.py is code-owned; new stress_budgets.json entries go through budget-raise-gate",
   notes=["Lands after F2.2 so budgets are recorded on the faster solve; after F1.1, which borrowed tests/replay.py.",
          "Also carries the solve-recompute class barrier if that RCA seat chooses a CPU budget."]),
 dict(id="F10.3", lane="F10", title="Owned gate scripts: verdict pins, mutation inventory, child-process closures; I1 and P11 barriers",
   findings=[("D7-s1-02", None), ("D14-s5-02", None), ("D14-s5-01", None)],
   edit=["tests/env_drift.py", "tests/stress.py", "tests/mutation_table.py", "tests/mutation_budgets.json",
         "tests/closure.py", "tests/derive_closures.sh", "tests/deployment_shape.py", "tests/doc_claims.py",
         "tests/ha_contract.py"],
   borrows={}, after=["F10.2", "F8.3", "F9.2", "F1.7"],
   tvofi="tests/env_drift.py, tests/stress.py, tests/mutation_table.py, tests/closure.py and tests/derive_closures.sh are code-owned; mutation_budgets.json may rise",
   notes=["D14-s5-02 is the I1 class barrier candidate (GUARD_OFF on any ast.If, CLAMP_DROP on numpy and multi-line min/max, a conditional-expression operator). No local mutation pools: count the inventory with its list mode, check one mutant in memory, and let CI's mutation lane evaluate.",
          "D7-s1-02 is weakened: lift the verdict loops into functions and pin them; note scenario_budget ran zero times under both drivers.",
          "D14-s5-01: record Python closures with strace on Linux as node already is; never run a full derive_closures.sh off Linux (gate-scoping.md).",
          "Waits on F9.2 (the last I1 pin PR) because the I1 barrier lands here, and on F1.7 because the P11 barrier does: P11's instances are F10.1's stubs, F1.1's replay clock, F1.7's Tibber reauth and F8.3's currency fallback. S4 proposes the P11 barrier as tests/ha_contract.py contracts for each, run nightly against the real package, never on the PR-blocking gate."]),
 dict(id="F10.4", lane="F10", title="Structural ratchet truth: dead members and uncounted helpers; I5 barrier",
   findings=[("D7-s3-01", None), ("D7-s3-72", None), ("D7-s3-02", None), ("D7-s1-01", None)],
   edit=["tests/structure.py", "tests/doc_claims.py"],
   borrows={CC+"coordinator.py": "F1", CC+"defrost.py": "F3", CC+"open_meteo.py": "F3", CC+"inputs.py": "F4",
            CC+"optimizer.py": "F2", CC+"thermal_model.py": "F2", "tests/open_meteo.py": "F1"},
   after=["F10.3", "F1.10", "F7.3", "F11.3"],
   tvofi="D7-s1-01 prices coordinator state reached through module-level helpers, which likely raises coordinator budgets: ask before the push",
   notes=["Last production-side PR of the round: it deletes members in files every other lane edits.",
          "The I5 barrier lands here because I5 has instances in five lanes (docs in F8, comments in F2.1, F2.3, F6.2 and F1.10, CLAUDE.md in F11.3); this PR waits on all of them. S2 proposes a nightly lane running its shape-checkers and failing on any false count; the RCA seat sizes it. A new script needs classifying and makes the PR tvofi's, which it already is.",
          "D7-s3-02 lands together with D7-s3-01's and D7-s3-72's deletions so dead_methods stays at its budget.",
          "D7-s1-01: if the honest re-record raises a structure budget, stop and ask tvofi before the push (CLAUDE.md rule 2)."]),
 # ---------------- F11 governance
 dict(id="F11.1", lane="F11", title="Governance parsers and enumerators (not code-owned)",
   findings=[("D11-s1-71", None), ("D13-s1-01", None), ("D11-s2-02", None), ("D11-s1-02", None), ("D11-s1-72", None)],
   edit=[".claude/workflows/policy_lint.mjs", ".claude/workflows/rules_sync.mjs", "tools/release/stamp.py"],
   borrows={}, after=[], tvofi=None,
   notes=["policy_lint.mjs and rules_sync.mjs are pinned, not owned: the change grades only after it merges.",
          "D11-s1-02 is weakened (capability, no incident): `rule4_problem` refuses a single-parent first-parent commit outside the stamp's write set.",
          "D11-s2-02: the hooks check reads each hook's matcher; a fixture with a wrong matcher pins it.",
          "D11-s1-72: the governance pin in tests/entities.py reads every workflow file, not governance.yml alone."]),
 dict(id="F11.2", lane="F11", title="Required-check boundaries (I3, owner-gated)",
   findings=[("D11-s1-01", None), ("D11-s1-04", None), ("D11-s1-03", None), ("D13-s1-03", None)],
   edit=[".github/workflows/tests.yml", ".github/workflows/pr-contract.yml", ".github/CODEOWNERS",
         ".claude/workflows/budget_raise_gate.py", "docs/decisions/0008-a-seat-identity-distinct-from-the-owner.md"],
   borrows={}, after=["F11.1"],
   tvofi="workflows, CODEOWNERS, budget_raise_gate.py and docs/decisions are code-owned; D11-s1-01 and D11-s1-04 are owner decisions",
   notes=["D11-s1-01: the remedy is a ruleset setting tvofi changes (dismiss stale reviews on push, or require last-push approval); the PR records it in decision 0008.",
          "D11-s1-04 (merged D11-s2-03): owner's decision between a distinct delegated identity and a refusal in budget_raise_gate.py.",
          "D11-s1-03 is weakened: the real seam is the pull_request trigger; a restore alone moves back with one tests.yml edit.",
          "D13-s1-03 is narrowed to the ordering gap: pr-contract is not re-run when the reds it lists finish."]),
 dict(id="F11.3", lane="F11", title="Policy text: per-file caps, CLAUDE.md rule 1, verdict carry on merges-only moves; I3 barrier",
   findings=[("D11-s2-01", None), ("D11-s2-04", None), ("D13-s1-02", None)],
   edit=[".claude/workflows/policy_lint.mjs", ".claude/workflows/policy_budgets.json", ".claude/rules/ratchet-budgets.md",
         ".cursor/rules/ratchet-budgets.mdc", "CLAUDE.md", "tools/audit/briefs/fix-review.md",
         ".claude/workflows/web-fix-wave.js", "tools/audit/app_approve.sh"],
   borrows={}, after=["F11.2"],
   tvofi="policy (CLAUDE.md, .claude/rules, tools/audit/briefs) and web-fix-wave.js are code-owned",
   notes=["D11-s2-04 is weakened: only claim (a) stands; quote the literal the select command prints.",
          "D13-s1-02 is weakened: a diff-equivalence carry saves a few rounds, not most; the owner decides whether to build it.",
          "Regenerate .cursor/rules with rules_sync.mjs after editing a rule.",
          "The I3 barrier lands here, not in F11.2, because D11-s2-01 (an I3 instance) is here and its barrier shape (the hooks matcher check and the per-file byte cap) lives in policy_lint.mjs and policy_budgets.json, which this PR edits.",
          "D11-s2-01's seams (S4): every file policy_budgets.json caps is an instance except CLAUDE.md, which the always-loaded aggregate guards; the fix is a per-file byte or token cap beside the line cap, or a zero band on the pooled aggregates. Any budget change here is tvofi's before the push."]),
 dict(id="F11.4", lane="F11", title="Class roster readers agree (I4 barrier); owed driver fixes",
   findings=[("D14-s2-03", None)],
   edit=["tools/audit/scopes.json", "tools/audit/check_scopes.py", ".claude/workflows/audit-find.js",
         ".claude/workflows/check-wave-script.mjs"], borrows={}, after=["F11.3", "F10.4"],
   tvofi="audit-find.js is code-owned",
   carry=["RESUME owed work that shares audit-find.js (fold only if tvofi agrees): the driver-fix PR for the round-9 Prepare defects (rounds interpolation, the earlier-rounds strip, the env_drift warm step, the Chromium path) and the batch patch's defer and judge-flag arguments; tools/audit/README.md naming scopes.json and check_scopes.py; the L2 scope gap (docs/decisions in no seat's scopes)."],
   notes=["The I4 barrier lands here, after every I4 instance: F11.1's parsers and GOV pin, and F10.4's dead_methods census (D7-s3-02), which is why this is the round's last PR. It does not move to F11.1, which precedes F10.4."]),
]
