#!/usr/bin/env python3
"""Builds rca_inventory.json and rca_scheduled.json (phase A / a2). Data transcribed from the sources named per row."""
import json, os

OUT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = "https://github.com/tvofi/heatpump_optimizer"
PLAN9 = "origin/handoff/audit-r9-plan@763b0ba4:handoff/round9/state/rca"
ISS = "origin/handoff/audit-r9-issues@788de96d:tools/audit/round9/issues"


def P(c=True, s=True, t=True, m=True):
    return {"cause": c, "process_state": s, "cost_test": t, "countermeasure_or_refusal": m}


def row(id, subject, trigger, date, docs, parts, state, cause, cost, cm, landed, status,
        reg=False, issue=(False, None), note=None):
    d = {"id": id, "subject": subject, "trigger": trigger, "date": date,
         "doc_locations": docs, "parts_present": parts, "process_state": state,
         "cause": cause, "cost_numbers": cost, "countermeasure": cm,
         "landed_sha_on_main": landed, "status": status,
         "documented_in_register": reg,
         "documented_on_issue": {"value": issue[0], "issue": issue[1]}}
    if note:
        d["note"] = note
    return d


rows = [
    # ---------------- era 1: doctrine landed #526 (2026-09-06) ----------------
    row("RCA-546-paired-artifacts", "#546 (released v6.3.17) and its class: paired-artifact divergence",
        "1 (release) + class (8 of 21 issues in one day)", "2026-09-06",
        [f"{R}/issues/541#issuecomment-5562486191", f"{R}/issues/201#issuecomment-5562840457"],
        P(), "(a)", "No process enumerates artifact pairs that must agree; every pin is reactive (card vs apply_topology schema).",
        "4.7 ms/run standing; registry refused (would cover 2 of 8)", "one check per pair (not a registry)",
        "137b6d59 (#548)", "done", issue=(True, 541)),
    row("RCA-593-preflight", "PR #593 red check (preflight.sh not in any local path)", "2 (red check)", "2026-09-07",
        [f"{R}/pull/593"], P(), "(a)", "The check existed and was in no local path; the earlier (b) answer was wrong.",
        "blanket pre-push re-record 16.5 s+ and partly prohibited (#527); triggered form fails its null control",
        "refused (owner-gated pre-push instruction named, not built)", None, "done",
        note="refusal; recorded in PR body only"),
    row("RCA-0002-self-witnessed-proxy", "check whose only witness is its author's model (7 instances)",
        "recurring class", "2026-09-09",
        ["origin/main:docs/decisions/0002-self-witnessed-proxy-assertion.md", f"{R}/pull/616"],
        P(), "(c)", "A check's acceptance is witnessed only by its author's model of it, so a proxy assertion passes on its own terms.",
        "one acceptance per mutation vs one adversarial review round per instance (7 in 2 days)",
        "mutation lane over the record mode's checks (#695) and the #616 lane", "1684e620 (#695); d7dc1423 (#616)", "done"),
    row("RCA-hassfest-toomanyrequests", "hassfest required context red on ghcr toomanyrequests (5x)",
        "2 (red required check)", "2026-09-09", [f"{R}/issues/201#issuecomment-5605144092"], P(), "(a)",
        "A required merge gate depended on a single unretried anonymous registry pull throttled per burst.",
        "5 of 16 attempts refused; retry ~0 s standing; passes at every measured base rate",
        "retrying warm-up docker pull in hassfest.yml", "a6e95ff9 (#689)", "done", issue=(True, 201)),
    row("RCA-690-record-status", "record-status class that took #690 four review rounds (5 instances)",
        "recurring class", "2026-09-09", [f"{R}/issues/201#issuecomment-5607513338"], P(), "(c)",
        "A Delivery-status disposition was a free-text assertion inside prose, not a field (6 spellings of one status).",
        "37 s standing vs ~3395 s x P=1.0/cycle (~90x)",
        "status check: roster arm (in-review requires pr) + bullet arm against API", "c9dfec77 (#691, roster arm)",
        "done", issue=(True, 201), note="bullet arm superseded by per-PR row files (#1081)"),
    row("RCA-scratchpad-body-swap", "#694 opened carrying #695's body (shared scratchpad)", "incident", "2026-09-09",
        [f"{R}/issues/201#issuecomment-5608473260"], P(t=False), "(a)",
        "No rule placed a seat's working files when several seats share one filesystem.", None,
        "per-seat mktemp -d proposed; built later as RCA-scratch-collide (#1092)", None, "partial",
        issue=(True, 201)),
    row("RCA-678-refusal-not-acted", "prepr.sh refusal printed and not acted on (4 instances)", "recurring class",
        "2026-09-09", [f"{R}/issues/678", f"{R}/issues/678#issuecomment-5608946006",
                       f"{R}/issues/201#issuecomment-5608945813"], P(), "(c)",
        "The detector ran and was right; nothing bound the push to its verdict (directory, grep filter, ignored exit, missing arg).",
        "9 instances 2026-09-09, 9 more 09-10 (measured rate)", "tools/audit/push.sh: contract-check at HEAD then push",
        "015fdbd8 (#715)", "done", issue=(True, 678)),
    row("RCA-533-nightly-unrun", "23 of 49 nightly checks merged/dispositioned never having run", "class (lane red, uncollected)",
        "2026-09-10", [f"{R}/issues/533#issuecomment-5616087353", f"{R}/issues/201#issuecomment-5616090514"], P(), "(a)",
        "Nothing compared the checks a lane declares with the checks it was observed to run; the schedule-only verdict had no collector.",
        "4 min < 240 min x 1.0 (~60x); 4 uncollected reds in 12 runs",
        "nightly-ha pull_request arm scoped to lane-touching diffs (proposed); two refusals", None, "prototype-only",
        issue=(True, 533), note="tests.yml nightly-ha still schedule/workflow_dispatch only at 3490cb16; #713 nightly-status (4e28724) is the related collector"),
    row("RCA-stated-number", "a stated number in a durable artifact (9 of 18 blocking rounds)", "recurring class",
        "2026-09-10", [f"{R}/issues/201#issuecomment-5618564043"], P(), "(c)",
        "The enumerator discipline had no grip on figures whose instrument was never run at the head they describe.",
        "9 of 18 blocking rounds; check refused (130 existing hits, fails coverage)",
        "writing rule (a measurement names its instrument), not a detector", "44f914ac (#724)", "done", issue=(True, 201)),
    row("RCA-541-wrong-audience", "'correct check, wrong audience' class (8 put, 3 verified)", "recurring class + main red",
        "2026-09-10", [f"{R}/issues/541#issuecomment-5622000848", f"{R}/issues/201#issuecomment-5622010287"], P(), "(c)",
        "A check's audience is set by a job's if:/argv, the one part no instrument executes (record job post-merge only).",
        "CM-2 0 seat-min/day vs ~36 seat-min/day; CM-1 refused at 5 false refusals per true one",
        "CM-2 record-status reported on every PR; CM-3 owner's call", "ae36eff1 (#738)", "done", issue=(True, 541)),
    row("RCA-541-stale-body-figures", "PR-body figures go stale at every merge (18 instances)", "recurring class",
        "2026-09-10", [f"{R}/issues/541#issuecomment-5624579071", f"{R}/issues/201#issuecomment-5624585324"], P(), "(a)",
        "Re-taking a figure is per-figure and manual while invalidation is per-commit and wholesale.",
        "27 min/PR vs 4.5 min (~6x) over 80 PRs", "fixer.md step 6 re-execution range extended to steps 7-8",
        "e64d287f (#793)", "done", issue=(True, 541)),
    row("RCA-541-gh-api-f", "gh api -f body=@FILE posts the literal path (5 events)", "recurring class", "2026-09-10",
        [f"{R}/issues/541#issuecomment-5625671141", f"{R}/issues/201#issuecomment-5625684379"], P(), "(c)",
        "-f is --raw-field; the call fails open (exit 0, HTTP 201) and a warning scored 0 of 3.",
        "0.15 s < 0.26 s per file-bodied comment (1.7x; 9.6x at day rate)", ".claude/workflows/gh_comment.py wrapper + read-back rule",
        "1fd24876 (#759)", "done", issue=(True, 541)),
    row("RCA-dev-record-quantity", "a quantity in the development record no enumerator ran (#768/#793, 6 instances)",
        "recurring class", "2026-09-11", [f"{R}/issues/201#issuecomment-5631076704",
                                         f"{R}/issues/201#issuecomment-5631258087"], P(), "(c)",
        "A quantity enters the record without its enumerator run against the artifact at its head; upstream, self-rows (43 of 198).",
        "41 min per claims-blocked round, 20 blocks/6 PRs; comparator 0 true findings -> refused",
        "refused (build nothing); moving-referent half closed by #793", None, "done", issue=(True, 201)),
    row("RCA-check-does-not-bind", "audit seat's own recurring defect: a null measurement rendered as a pass (3)",
        "recurring class", "2026-09-11", [f"{R}/issues/201#issuecomment-5632481833"], P(), "(c) [+ (b) for occurrence 3]",
        "An empty array / wrong path produced output indistinguishable from a passing measurement.",
        "+0.07 s per check authored vs ~5.3 min x 1.0/session",
        "assert_binds + safepost.sh (seat-local tools)", None, "prototype-only", issue=(True, 201),
        note="countermeasure never entered the tree"),
    row("RCA-865-pr-body-live-object", "#860 item 4: pr-contract cannot be green at every head", "recurring class",
        "2026-09-11", [f"{R}/issues/865", f"{R}/issues/201#issuecomment-5636576381"], P(), "(c)/(a)",
        "The PR body is one mutable object; every head's contract job reads the current body.",
        "stated on #865 (not re-read here)", "refused: no check; S10 order kept; HANDOVER decision (#868)", None, "done",
        issue=(True, 865)),
    row("RCA-trap13-instance-vs-property", "#531/#569/#591: a fix verified against the demonstrated instance",
        "recurring class", "<=2026-09-10", ["origin/main:docs/HANDOVER.md (trap 13)"], P(s=False), None,
        "The demonstration displaces the specification; verification is built from the instance's form.",
        "3.1% of reviewed PRs, 11.2% of review rounds; preflight.sh catches 0 of 3",
        "refused (a check cannot close it)", None, "partial", note="original analysis comment not located; process state not in surviving record"),
    # ---------------- era 2: wave 4 / governance session ----------------
    row("RCA-1041-plan-d6-conflicts", "#1041 plan-row and D6 claims merge conflicts (4 in one wave)", "recurring class (3rd+)",
        "2026-09-15", [f"{R}/issues/1041#issuecomment-5673831824", f"{R}/issues/201#issuecomment-5673843364"], P(), "(c)",
        "Two mechanisms: appends concentrated at one anchor, and PYTHONHASHSEED-dependent set repr in D6 claims.py.",
        "A ~0 s standing vs 15-70 min/wave; machine-readable rows fail (+10-20 min/wave vs 4-10)",
        "deterministic sorted-set render in D6 claims.py; plan-row redesign refused", "3aa1351d (#1051)", "done",
        issue=(True, 1041)),
    row("RCA-1041-silent-zero", "silent-zero class: a clean count over a set never enumerated (5 instances, 1 on the release path)",
        "1 (stamp.py rule 4 blind across releases) + class", "2026-09-16",
        [f"{R}/issues/1041#issuecomment-5693093076", f"{R}/issues/1041#issuecomment-5693711890",
         f"{R}/issues/1041#issuecomment-5693870772", f"{R}/issues/1041#issuecomment-5694083243",
         f"{R}/issues/201#issuecomment-5693138924"], P(), "(d) residual 3/stamp; (a) residual 2; (c) Approval hole and class",
        "A derivation's failure path returns the success path's empty value; main's merge-subject shape changed unrecorded.",
        "0.07-0.08 s/run, 12.8 s per window; break-even 3.2 s per occurrence; lint refused at 8/55 precision",
        "merge_shape_guard.py (built, not pushed); instance fixes #1054-#1057 and ADR 0010", None, "prototype-only",
        issue=(True, 1041), note="instances fixed (#1057 ed875dea); the guard never landed; owed cost-test re-run (4 post-analysis sightings)"),
    row("RCA-delivery-row-seam", "Delivery-status rows collide at one shared seam (31 of 40 merges)", "recurring class (owner-ordered)",
        "2026-09-16", [f"{R}/issues/201#issuecomment-5704098870", "origin/main:docs/delivery/1081.md"], P(), "(c)",
        "The rule sends every new row to the same append point, so concurrent PRs conflict at one base position.",
        "~16 seat-min + 9.5 runner-min per merge vs ~0 s; option (a) refused 30/31",
        "(d) one row file per PR, plan table frozen", "31384db6 (#1081)", "done", issue=(True, 201)),
    row("RCA-ledger-self-loop", "ci/delivery-ledger lane re-triggering itself (9 of 11 ledger PRs self-opened)",
        "recurring class", "2026-09-16", [f"{R}/issues/201#issuecomment-5705776367 (NOT FOUND: deleted)",
                                         "origin/main:docs/delivery/1086.md"], P(t=False), "(d) per PR #1086 body",
        "Merging a ledger PR is a push to main that re-runs the publisher, which opens the next ledger PR.",
        None, "publish splices #201 directly; commits/pushes/opens nothing", "34efcbae (#1086)", "partial",
        note="RCA comment deleted; cost test not recoverable"),
    row("RCA-gate-lease-full", "three unleased FULL gates on 2026-09-16 (#1072, #1074, #1068)", "incident/class",
        "2026-09-16", ["RCA comment on #201 (not found)", "origin/main:docs/delivery/1089.md"], P(s=False, t=False), None,
        "run.sh did not take the gate lease itself for FULL/stress runs.", None,
        "run.sh self-leases (gate_lock.py needs-lease/auto-lease)", "a9dbb68e (#1089)", "partial",
        note="PR #1089 API 404 (author tvofi-seat-author); analysis not retrievable"),
    row("RCA-scratch-collide", "shared scratchpad/tmp names and pattern kills destroyed seats' outputs (09-16/17)",
        "recurring class", "2026-09-17", ["RCA comment on #201 (not found)", "origin/main:docs/delivery/1092.md"],
        P(s=False), None, "Seats of one session share one scratchpad, /tmp and process table; generic names collide.",
        "cause, process state and cost test stated to be on #201 (comment not found)",
        "prepr.sh/gh_comment.py refuse body files in shared roots; orchestrator.md §5", "b673df87 (#1092)", "partial",
        note="PR #1092 API 404; RCA comment missing from #201"),
    row("RCA-1087-friction-measurement", "#1087 friction key fixer.md: an issue carried a measurement and no perturbation",
        "recurring friction", "2026-09-17", [f"{R}/issues/1087#issuecomment-5719932299 (NOT FOUND)",
                                            "origin/main:docs/plan-2026-09-open-issues.md (#1087 disposition)"],
        P(), "(d)", "A friction count is a property of the keying rule and already-merged bodies, not of what seats write.",
        "two further countermeasures refused on cost (numbers not recoverable)",
        "friction_issues.mjs bodyFor states what the count is a property of", "c71c53cf (#1118)", "done",
        issue=(False, 1087), note="RCA comment no longer on #1087; parts known only from the plan's summary"),
    row("RCA-1094-relative-scratch", "#1094: seats created scratch dirs in the orchestrator's checkout", "recurring friction",
        "2026-09-17", [f"{R}/issues/1094#issuecomment-5720431439 (NOT FOUND)", "origin/main:docs/delivery/1123.md"],
        P(t=False), "(c)", "orchestrator.md §5 prescribed a relative scratchpad/<seat>/ path resolving against the seat's cwd.",
        None, "§5 requires an absolute path and the seat's own worktree", "3a012f66 (#1123)", "partial",
        issue=(False, 1094), note="RCA comment deleted"),
    row("RCA-1095-typing-census", "#1095 gate-scoping: mypy census invisible to a green local gate", "recurring friction",
        "2026-09-17", [f"{R}/issues/1095#issuecomment-5719981924 (NOT FOUND)", "origin/main:docs/delivery/1122.md"],
        P(s=False), None, "run.sh's typing lane was source-only; the mypy census ran only in CI's typing job.",
        "5 of 45 merged PRs in v6.5.1..main paid a push-CI-fix round", "typing_ruler.py guard 5 (HPO_TYPING_PYTHON)",
        "e467026a (#1122)", "partial", issue=(False, 1095), note="RCA comment deleted"),
    row("RCA-mutation-lane-baseline", "mutation lane: red baseline refused PRs though no mutant ran", "recurring (lane)",
        "2026-09-17", ["root-cause seat on #201 (comment not found)", "origin/main:docs/delivery/1120.md"],
        P(s=False, t=False), None, "A red baseline evaluated zero mutants but read as a refusal on scoped PR runs.",
        None, "baseline_refusal(): INCONCLUSIVE on PR scope, refuse on nightly full", "6bbc0bfa (#1120)", "partial",
        note="PR #1120 API 404"),
    row("RCA-vacuous-acceptance-arm", "generalised vacuous-acceptance-arm detector (4th instance)", "recurring class",
        "2026-09-17", [f"{R}/issues/201#issuecomment-5720829142 (NOT FOUND)", "origin/main:docs/HANDOVER.md"],
        P(s=False), None, "Three shapes, not one: harness decoupled from mutated code, environment precondition, false prose claim.",
        "37 historical instances ~100% caught pre-main (seat's own figure); ~1 review round per defect",
        "refused on cost", None, "partial", note="process state not in surviving record"),
    # ---------------- era 3: rounds 6-8 ----------------
    row("RCA-1336-d9-memory-arm", "#1336 D9 memory stale arm read a declined attributable as fine", "carry",
        "2026-09-21", [f"{R}/pull/1371"], P(t=False), "(c)", "The guard-and-pin process was followed; the pinned selftest covered one axis.",
        None, "carry to the judging stage", "24df6743 (#1371)", "partial"),
    row("RCA-1293-d0-refutation", "#1293 refutation: D0 findings that cost more than they save (4)", "recurring class",
        "2026-09-22", [f"{R}/pull/1372"], P(), "(a)", "No process made a D0 seat report measured cost beside a finding.",
        "stated in PR body (second instance in one wave)", "cost-aware D0 finding format, requested of the owner",
        None, "prototype-only", note="#1372 (2a71bc3e) landed the refutation command only"),
    row("RCA-1485-ledger-line-shift", "mutation ledger re-pointed after D7-01 line shift", "2 (red check: briefs)",
        "2026-09-23", [f"{R}/pull/1485"], P(t=False), "(a)",
        "A production line shift invalidates a path:line citation in a carry outside the diff; no local run of the linter.",
        None, "not built (policy edit recorded)", None, "partial"),
    row("RCA-1499", "#1499 Heat Pump Action / hvac_action off on DHW-only steps", "1 (128 of 128 tags)", "2026-09-23",
        [f"{R}/issues/1499#issuecomment-5803725714"], P(), "(c)",
        "The action ladder reads space power only; DHW co-optimisation moved the precondition and the consumer did not.",
        "230 min x 0.023/release = 5.4 min/release; break-even ~19 min per D8 round; invariant check refused (0 value)",
        "D8.md step 2 oracle: operating state vs the plan's own draw", "f8630d95 (#1504)", "done", issue=(True, 1499)),
    row("RCA-1514", "#1514 body edit re-creates required contexts as skipped (regression of #1484)",
        "plan-assigned (regression of a fix; strict triggers not met)", "2026-09-24",
        [f"{R}/issues/1514#issuecomment-5805916237"], P(), "(c)",
        "#1484's edited-event if: guards made three required contexts re-report skipped at an existing head.",
        "1,800 s x 0.25 = 450 s vs ~20 s/cycle (>20x)",
        "pr-contract in its own workflow; pin keyed on required-contexts.json", "e2e8c3bf (#1558)", "done",
        issue=(True, 1514)),
    row("RCA-1515", "#1515 required checks run unowned PR code (regression of #1402/#1403)", "1 (v6.6.10)", "2026-09-24",
        [f"{R}/issues/1515#issuecomment-5805916471"], P(), "(a)",
        "Two round-6 fixes each closed their instance; neither checked the shared restore-or-own invariant (8 files).",
        "1,800 s x 0.5 = 900 s vs ~90 s/cycle (~10x)", "standing transitive owner walk over required contexts",
        "e2e8c3bf (#1558)", "done", issue=(True, 1515)),
    row("RCA-1525", "#1525 sysid refusal silent while published status says success", "1 (v6.6.10)", "2026-09-24",
        [f"{R}/issues/1525#issuecomment-5819869321"], P(), "(a)",
        "#1437 moved the quality refusal from a named producer path to the consumer's silent guard and deleted the pin.",
        "0.01 s/run vs hours x P>0.01/change; wider disposition rule refused (~135 min/month, ~0 efficacy)",
        "check: cases drive every return of _adopt_system_identification", "6180d5b7 via 14d7a276 (#1581)", "done",
        issue=(True, 1525)),
    row("RCA-R8-P9-1522", "R8-P9 #1522 zoom controls after the chart in Tab order", "round-8 class (plan §6)", "2026-09-24",
        [f"{R}/pull/1553"], P(), "(a)", "Overlay controls emitted after the svg; no check asked focus order in space.",
        "browser-lane wall time delta (in Figures)", "focus-order arm in card_browser", "30ab40a0 (#1553)", "done",
        note="fixer-embedded, not a separate seat"),
    row("RCA-R8-P8-1513", "R8-P8 #1513 unit normalisation + _current_weather regression", "round-8 class", "2026-09-24",
        [f"{R}/pull/1559"], P(), "(a); regression (c)", "Units normalised one family at a time where a defect surfaced; readers outside InputReader never enumerated.",
        "~1.1 s static check; 10 sites at base, 7 defects", "static unit check + convert at storage", "c59672bc (#1559)", "done",
        note="fixer-embedded"),
    row("RCA-R8-I5b", "R8-I5b doc/comment/string drift (#1534-#1537)", "round-8 class", "2026-09-24", [f"{R}/pull/1560"],
        P(), "(a)", "No machine-checked agreement between README/catalogs/comments and the artifacts they describe.",
        "unmeasurable vs ~1 s doc_claims run", "doc_claims.py arms 4-5", "4ae0b93a (#1560)", "done", note="fixer-embedded"),
    row("RCA-R8-I1a-kill-rule", "R8-I1a mutation kill counted on exit status (#1521, #1531)", "round-8 class", "2026-09-24",
        [f"{R}/pull/1561"], P(), "(c)", "Exit status carried both 'a check failed' and 'I refuse to measure'.",
        "regex over captured output + ~1 s; null control in its own tree", "kill = failing check named in output; comment-only null control",
        "6acd85ac (#1561)", "done", note="fixer-embedded"),
    row("RCA-R8-P12-1517-1529", "R8-P12 away envelope unconditional restore (#1517) and diagnose_interval hand-off (#1529)",
        "round-8 class", "2026-09-24", [f"{R}/pull/1563"], P(), "(a)",
        "Envelope assumed no writer between apply and restore; hand-offs listed by name, not enumerated.",
        "0.62-0.78 s entities block", "compare-and-restore by identity; executor hand-off allow-table", "97dc04f2 (#1563)",
        "done", note="fixer-embedded; the same hub-write class later got RCA-1736"),
    row("RCA-R8-P1", "R8-P1 #1518/#1519/#1541 non-finite leaves, Open-Meteo parse, platform scrub", "round-8 class",
        "2026-09-24", [f"{R}/pull/1569"], P(), "(c) #1518; (a) #1519/#1541",
        "finite_boundary substituted only present leaves and non-finite spellings; parse and scrub seams unenumerated.",
        "CPU delta of two scripts (in body)", "three arms in finite_boundary/entities", "8658ef6a (#1569)", "done",
        note="fixer-embedded"),
    row("RCA-R8-P2", "R8-P2 hot-water entity gate (#1527, #1542)", "round-8 class", "2026-09-24", [f"{R}/pull/1572"], P(), "(a)",
        "'Is this input configured' had no single owner; each fix repaired only listed members.", "1.12 s upper bound",
        "two population-keyed barriers in entities.py", "4b2a7d8c (#1572)", "done", note="fixer-embedded"),
    row("RCA-R8-P6-1526", "R8-P6 #1526 heat-pump switch actuated via switch.* only", "round-8 class", "2026-09-24",
        [f"{R}/pull/1576"], P(), "(a)", "Slot accept-list widened (v3.14.0) while its one consumer kept a switch.* literal.",
        "0.06-0.14 s census", "accept-list vs consumer route census", "d48d9e9c (#1576)", "done", note="fixer-embedded"),
    row("RCA-R8-P5-1523", "#1523 sysid ignored the learning freeze (released)", "1 (release)", "2026-09-24",
        [f"{R}/pull/1581"], P(), "(a)", "Learner freeze added one learner at a time; nothing enumerated functions feeding a persisted learner.",
        "0.24 s (two AST walks)", "class check over coordinator.py", "14d7a276 (#1581)", "done", note="fixer-embedded"),
    row("RCA-1546", "#1546 untranslated UpdateFailed raises (released)", "1 (release)", "2026-09-25", [f"{R}/pull/1590"],
        P(), "(a)", "The yaml's claims were prose nothing executed; hassfest skips the file for a custom integration.",
        "0.73-0.91 s per run", "two doc_claims.py arms", "f5d4743b (#1590)", "done", note="fixer-embedded"),
    row("RCA-R8-P3", "R8-P3 COP priced by two sibling paths (wood/DHW)", "round-8 class", "2026-09-25", [f"{R}/pull/1602"],
        P(), "(a)", "The simulation gained humidity and the valve law; the planner helpers' call sites were never enumerated.",
        "3 AST parses + 480 marginal_cop calls inside features.py", "seam rule + law property", "d449a3b1 (#1602)", "done",
        note="fixer-embedded"),
    row("RCA-R8-I3-1516", "#1516 published tag tree not checked to be on main", "round-8 class", "2026-09-24",
        [f"{R}/pull/1558"], P(), "(a)", "#960's fix pinned uses: refs and attested the tag tree without asking whether it was reviewed.",
        "one git fetch + merge-base per release", "release-ancestry workflow step", "e2e8c3bf (#1558)", "done",
        note="fixer-embedded"),
    row("RCA-1567-unpinned-installs", "installs inside SHA-pinned jobs unpinned", "round-8 class", "2026-09-24",
        [f"{R}/pull/1567"], P(), "(a)", "#960 pinned uses: refs; nothing in the gate read an install command.",
        "0.36 s per entities.py run", "lock files + barrier", "7af2a261 (#1567)", "done", note="fixer-embedded"),
    row("RCA-1566-stats-head-moved", "policy_lint --stats head-moved keyed on the first verdict", "round-8 hygiene",
        "2026-09-24", [f"{R}/pull/1566"], P(), "unlettered (detector tested only on its source window)",
        "#1405 keyed rework against the first verdict's head; pins transcribed one window.", "4 entries/window; separate check refused",
        "one-per-shape synthetic fixture", "ca8204f4 (#1566)", "partial", note="state not lettered a-d"),
    row("RCA-1595-nan-ratchets", "ratchets fail open on a non-finite recorded budget", "class", "2026-09-24", [f"{R}/pull/1595"],
        P(), "unlettered ('class never named')", "Each ratchet trusted the recorded side to be a number; NaN comparisons are false.",
        "no measurable runtime; ~45 lines", "shared finite-budget barrier per ratchet", "be9a9d58 (#1595)", "partial",
        note="state not lettered a-d"),
    row("RCA-1565-mutation-timeouts", "CI mutation job 90-minute timeouts", "recurring (lane)", "2026-09-24",
        ["origin/main:docs/delivery/1565.md", "RELEASE_NOTES.md (#1565)"], P(s=False, t=False), None,
        "Baselines and survivor sweeps ran serially on one worker tree.", None,
        "spread over worker trees; mutate touched lines; 160-min job", "0974905c (#1565)", "partial",
        note="PR body not retrievable via search/API"),
    row("RCA-1577-ledger-anchors", "mutation ledger DIRTY cascade on concurrent branches", "recurring class", "2026-09-24",
        [f"{R}/pull/1577"], P(), "(a)", "#1412 chose a committed count and positional keys; nothing measured how the file merges.",
        "0-25 CPU s per mutation run", "ledger keyed by content anchor; count derived at merge base", "3063c1ce (#1577)", "done"),
    row("RCA-1584-root-cause-unanswered", "#1584 root-cause-unanswered blocks (5 in window, 23 since 09-06); #1585", "recurring friction",
        "2026-09-24", [f"{R}/pull/1601"], P(), "(c)",
        "The red check concluded after the blocked head was pushed; a fixer cannot answer a check not yet run.",
        "stated in body (class search 23 verdicts)", "recorded refusal; fixer.md route for #1585", "48426266 (#1601)", "done"),
    row("RCA-1596-gate-lease-wait", "#1596 gate-lease waits of hours (4 of 5 entries)", "recurring friction", "2026-09-24",
        [f"{R}/pull/1603"], P(), "(d)", "A single-holder lease was sound for few seats; round 8's seat count changed that.",
        "stated in body", "bounded wait; stress.py to CI past one lease period", "5bc99ceb (#1603)", "done"),
    row("RCA-1589-policy-docs-red", "policy-docs red on main after #1589 (+#1592)", "2 (red on main)", "2026-09-25",
        [f"{R}/pull/1604"], P(t=False), "(c)", "Semantic conflict between two independently green PRs.",
        None, "re-own delivery_status.py and nightly_status.py", "fab69590 (#1604)", "partial",
        note="RC1 (2026-09-26) later found codeowners_gap red on 8 main commits, 5 h 24 min"),
    row("RCA-coil-drain", "DHW planner wood forecast re-derived coil drain (R8-P3 carry)", "round-8", "2026-09-25",
        ["origin/main commit e6a26880"], P(s=False, t=False), None,
        "The wood forecast re-derived the refill coil's drain beside the physics that couples it (+2.08 K).",
        None, "features.py check (red until R8-P3 reads the trajectory)", "e6a26880 via 23eaf856 (#1605)", "partial"),
    # ---------------- era 4: v6.6.12 escape ----------------
]

V = "origin/handoff/v6612-root-cause:tools/audit/handoff/v6612-root-cause.md"
rows += [
    row("V6612-bug5-switch", "v6.6.12 bug 5 (switches flip back on) and class P11", "1 (v6.6.12)", "2026-09-25",
        [V, f"{R}/pull/1621"], P(), "(a)", "is_on read the published payload and no action wrote state; the stub had no async_write_ha_state.",
        "sweep 0.007 s standing; 1 escape + 2 latent", "entity-action sweep in tests/entities.py", "8f7abb96 via 6ce591a5",
        "done", reg=True, note="no issue exists; record lives in PR bodies"),
    row("V6612-listener-callback", "v6.6.12 arbiter listener not @callback", "1 (v6.6.12)", "2026-09-25", [V], P(), "(c)",
        "ha_contract filed callback as DIVERGENT (no event loop in any lane): a record instead of a barrier.",
        "~0 per registration; 2 instances", "stub callback tags; async_track_state_change_event refuses untagged sync fn",
        "d9a46139 via 9b60705e (#1619)", "done", reg=True),
    row("V6612-bug3-4-echo", "v6.6.12 bugs 3/4 and the 25 °C reset (fork's 8 s echo read as landed)", "1 (v6.6.12)",
        "2026-09-25", [V, "origin/handoff/v6612-rc-policy:tools/audit/handoff/v6612-rc-policy.md"], P(), "(d)",
        "Review ran the implementer's fake pump; the judge's P4 and M5 reached release untested and unwaived.",
        "one design trace per feature PR; 1 feature, >=5 defects", "owner ruling (hold what it wrote) + fix-review design-trace step",
        "13852148 (#1619); 7b663b02/a3f04435 via 7c87d69b (#1625)", "done", reg=True),
    row("V6612-bug1-6-ownership", "v6.6.12 bugs 1 and 6 (arbiter's own DHW-only read as a block)", "1 (v6.6.12)",
        "2026-09-25", [V], P(t=False), "(c)", "Ownership held only when the persisted record matched the last mode written.",
        None, "none beyond the fix (cannot recur under the ruling)", "13852148 (#1619)", "partial", reg=True),
    row("V6612-bug2-lease", "v6.6.12 bug 2 (90-min DHW-only lease into a warm house)", "1 (v6.6.12)", "2026-09-25", [V],
        P(t=False), "(a)", "The lease counted idle steps and released regardless of room temperature.",
        None, "refused: cheapest detector was field use", None, "partial", reg=True, note="refusal without numbers"),
    row("V6612-bug7-card-history", "v6.6.12 bug 7 (card history by position)", "1 (v6.6.7-v6.6.12)", "2026-09-25",
        [V, "origin/handoff/v6612-history-shape:tools/audit/handoff/v6612-history-shape.md"], P(), "(a)",
        "The rig's historyApi returned one list per id in order; HA drops empty lists and filters by default.",
        "2 detected escapes in 6 releases; capture ~5 min then one fixture compare", "rig serves HA semantics; real /api/history/period capture pinned",
        "6caefba8 via 1f032bd4 (#1622); 3f9f7708 via d1e07037 (#1626)", "done", reg=True),
    # ---------------- round 9 ----------------
    row("R9-RC1-pinned-local", "#1633 red trigger: codeowners_gap graded on base copy only", "2 (red check)", "2026-09-26",
        ["origin/handoff/audit-r9-plan@763b0ba4:handoff/round9/rca/RC1-root-cause-section.md",
         "origin/handoff/r9-rc1-pinned-local-r2:tools/audit/handoff/r9-rc1-pinned-local.md", f"{R}/pull/1637"], P(), "(c)",
        "Pinned jobs grade the base copy on PRs and the head copy on main; prepr.sh never ran codeowners_gap.",
        "31-88 s/release + 4.1 s vs P 0.2-0.6/release x >=6-18 min (escaped instance 5.4 h)",
        "prepr.sh steps 3e-3g (run pinned graders locally; refuse an unrun one)", "b6234f2c (#1637)", "done",
        issue=(False, None), note="recorded in PR #1633/#1637 bodies"),
    row("R9-RC2-bug5-reboot", "v6.6.12 bug 5 'all toggles on after reboot'; class N-restart", "1 (v6.6.12)", "2026-09-26",
        ["origin/handoff/audit-r9-plan@763b0ba4:handoff/round9/rca/RC2-bug5-reboot.md (brief)",
         "origin/handoff/r9-rc2-user-state-durable:tools/audit/handoff/r9-rc2-user-state-durable.md", f"{R}/pull/1641"],
        P(), "(d) queue; (a) mode; (c) #1621's check",
        "HA 2026.5 single-entity calls take the PARALLEL_UPDATES slot while actions awaited a 33-73 s solve; mode persisted at cycle end.",
        "0.023 s/run (~3.4 s/release) vs 0.028/release x 8 h = 13 min", "RC2 durability block in tests/features.py",
        "4f25b5e3 (#1641); R6 8cca77bc (#1638)", "done", reg=True, issue=(False, 1662),
        note="#1662 issue draft said 'RCA: owed'; the RCA lives in PR #1641"),
    row("R9-1638-clobbered-store", "R6 regression: setter save overwrote the store before the startup load", "none (record only)",
        "2026-09-26", [f"{R}/pull/1638"], P(t=False), "(c)", "A whole-store save moved into a setter was not ordered after the load.",
        None, "in-flight ordering fix in #1638", "8cca77bc (#1638)", "partial"),
]

CLS = [
    # id, slug, class, issue, state, cause, cost, cm, landed, status, reg
    ("R9-P2", "p2", "P2", 1644, "(c); D12-s2-02 (d)", "Each site decides a shared fact with its own local copy of the rule; nothing names one owner.",
     "~5 min/round (2.1-2.5 s x 123 runs) vs P ~6.3 instances/round", "one-fact-one-owner registry lint (P2 owners block, F1.11)", None, "prototype-only", False),
    ("R9-I5", "i5", "I5", 1645, "(c) [earlier rounds recorded (a)]", "A code-owned fact is restated by hand in prose with no derivation link.",
     "14.7 min CPU / 24.1 min wall per round vs >=17.5 min per instance x 19", "five corpus-wide doc_claims arms (F10.4) + quoted-line citation pass (F11.3)",
     "quoted-line pass only, via 87d780c7 (#1715)", "prototype-only", False),
    ("R9-I1", "i1", "I1", 1646, "(c)", "The count ratchet refuses only a grown total, so a trade nets to zero (28 content-new unpinned sites in 10 merges).",
     "net -20 s CPU/run (inventory 21.8 s -> 1.3 s); ~0.5 human verdicts/merge", "per-site mutation ratchet + widened inventory (F10.3)", None, "prototype-only", False),
    ("R9-P1", "p1", "P1", 1647, "(c)", "QuarantiningStore covers only non-finite; naive instant, wrong type, magnitude and container stay per-seam.",
     "~53 min/round (26 s x ~123 runs) vs >=8.1 h/round (9.1 h x 0.89)", "magnitude scrub in store.py + finite_boundary Arm 4 (F1.6)", None, "prototype-only", False),
    ("R9-I3", "i3", "I3", 1648, "(c); D11-s1-01 (d)", "Each governance check reads only the fields its motivating defect varied.",
     "17.5 s CPU/full run vs 96-310 min per instance x 3.75/round", "field_coverage.mjs registered-check field coverage (F11.3)",
     "767ab2c4 via 87d780c7 (#1715)", "done", False),
    ("R9-P11", "p11", "P11", 1649, "(c); currency/Tibber routes (a)", "The only oracle for an external counterpart is a double written from what the code needed.",
     "1.5 min/release vs 18.8 min/release (~12x)", "ha_contract.py: non-vacuity, hook re-runs, declared drops (F10.1)",
     "1c711375 via 1ef6a805 (#1693)", "done", True),
    ("R9-I4", "i4", "I4", 1650, "(a)", "Governance tooling has no one-definition rule; a concept's second reader is never compared.",
     "~2.8 min x k per round vs 200-879 min/round", "agreement lane + grammar discovery (F11.4)", None, "prototype-only", False),
    ("R9-P6", "p6", "P6", 1651, "(c)", "Consumers read through silent-fallback lookups; each guard took its universe from one instance.",
     "stated per round vs >=72 min/round (2.56 x 28 min)", "'every read has a producer' section, 7 arms (F1.11)", None, "prototype-only", False),
    ("R9-P9", "p9", "P9", 1652, "(c)", "The card's CI witness is keyed to past instances; the property is measured only by the audit.",
     "~3.3 runner-h/round (18.5 s -> 152.6 s x 88 PRs) vs 2.7 instances/round", "p9Grid rendered-property rules over a state grid (F6.3)", None, "prototype-only", False),
    ("R9-N-solve-recompute", "avoidable-interpreter-bound-recomputation", "N-solve-recompute", 1653, "(c)",
     "Batch twins run the scalar body per row; #985 was accepted on the proxy count, not CPU.",
     "5,700 < 7,100 x 0.56 x N_tariff s/round", "production-call channel in stress.py (F10.2)", None, "prototype-only", False),
    ("R9-P3", "p3", "P3", 1654, "(c)", "Each sibling writes its normalisation of a shared quantity inline at the point of use.",
     "1.0 CPU-s/run; break-even ~28,000 runs/round (10 h x 0.78)", "one floor per thermal parameter + one floor price per zone (F1.10)", None, "prototype-only", False),
    ("R9-P5", "p5", "P5", 1655, "(c)", "adoption_decision bounds the fit's precision, which cannot see bias from what the experiment is told.",
     "3.9 CPU-s/run vs >=7.9 h x 1.0/round", "adoption sweep perturbs told quantities (F4.2)", "2e91e219 via fab17619 (#1718)", "done", True),
    ("R9-N-cpu-gate-blind", "cpu-gate-blind", "N-cpu-gate-blind", 1656, "(c)",
     "CPU gates judge aggregates or hand-named seams; DETECTION_TARGET proves only a 2x of the figure itself.",
     "per-part standing cost vs ~6,900 s/round per tariff install; 8 of 9 rounds", "plant-axis coverage + loop-thread CPU figure (F10.2)", None, "prototype-only", False),
    ("R9-N-future-instant", "persisted-future-instant-trusted-without-bound", "N-future-instant", 1660, "(c)",
     "A stored instant from a clock that ran ahead is trusted verbatim; the load boundary checks finiteness only.",
     "1 s vs 0.038/release x 3.5 h = 480 s/release", "QuarantiningStore(lead=) + finite_boundary Arm 5 (F3.1)",
     "74a4e17d via 917f16c2 (#1691)", "done", True),
]
BR = {"p2": "3938c8ea", "i5": "c6ba6036", "i1": "8eda51a2", "p1": "0ade2456/99118d35", "i3": "844d14b7", "p11": "82e645c3",
      "i4": "06bae072", "p6": "aa2026b7", "p9": "4f3b9d4f", "avoidable-interpreter-bound-recomputation": "ab04e39b",
      "p3": "2ca057ae", "p5": "d4cf63d9", "cpu-gate-blind": "8352c9e0", "persisted-future-instant-trusted-without-bound": "8795c4c2"}
for (id, slug, cls, iss, st, cause, cost, cm, landed, status, reg) in CLS:
    docs = [f"{PLAN9}/{slug}/RCA.md", f"origin/handoff/r9-rca-{slug}@{BR[slug]}", f"{ISS}/{slug}.md", f"{R}/issues/{iss}"]
    if slug in ("i3", "i4", "p2"):
        docs.insert(1, f"origin/handoff/r9-rca-{slug}:tools/audit/round9/rca/{slug}/RCA.md")
    rows.append(row(id, f"class {cls} (#{iss})", "class (N>=3 in round 9; judge rca:true)"
                    + ("; sweep raised N to 8" if slug.startswith("persisted") else ""), "2026-09-26", docs, P(), st, cause, cost,
                    cm, landed, status, reg=reg, issue=(True, iss),
                    note="Root cause section in issue body (verified on #1647; others per drafts at 788de96d, filed 19:35Z after)"))

rows += [
    row("R9-RCA-1736", "#1736 solve-scoped hub writes (5 instances over 3 rounds)", "1 (115 releases) + cross-round class",
        "2026-09-28", ["origin/handoff/r9-eg-b0:handoff/round9/state/alt/RCA-1736.md", f"{R}/issues/1736#issuecomment-5877263448"],
        P(), "(a) landing; (c) recognition", "The configured hub objects double as the solve's input-assembly surface, carrying two meanings.",
        "0 standing vs 4.6/month x 18.4 h = ~85 h/month", "EG-B1 per-solve immutable inputs; fold class into bugclasses.json; widen barrier window (policy, proposed)",
        None, "prototype-only", issue=(True, 1736), note="no prototype built; EG-B1 not started"),
    row("R9-1728-stamp-invariant", "v6.7.8 stamp broke may-drift/claimed-for-VERSION (main red)", "2 (red on main)", "2026-09-27",
        [f"{R}/pull/1728"], P(t=False), "unlettered", "The R8-P3 coverage ruling was enforced only in entities.py, which no stamp run executes.",
        None, "coverage rule moved into env_drift --claims-only (stamp self-check)", "f9c081fe (#1728)", "partial"),
    row("PRE-70-v511-freeze", "v5.1.1 options save froze the instance (pre-doctrine)", "1 (release)", "2026-08-27",
        [f"{R}/pull/70"], P(s=False, t=False, m=False), None,
        "Every options page saved on exit, forcing a reload whose setup awaited a full cold solve holding the GIL.",
        None, None, None, "partial", note="predates #526 doctrine"),
    row("PRE-1249-picker-revert", "cleared entity picker reverted (released; later an N-restart instance)", "1 (release)",
        "2026-09-19", [f"{R}/pull/1249"], P(s=False, t=False, m=False), None,
        "HA's flow manager re-runs a submitted post through the step schema, restoring the stored default.",
        None, None, None, "partial"),
]

json.dump(rows, open(os.path.join(OUT, "rca_inventory.json"), "w"), indent=1, ensure_ascii=False)

FP = "origin/handoff/audit-r9-fixplan"
AR = "origin/handoff/audit-r9-alt:handoff/round9/state"
sched = [
    {"subject": "#1747 DHW block ignored by the co-optimisation replan (Root cause section owed on the issue)",
     "where": [f"{AR}/ALT-ROSTER.json group R9-EG-B8 brief", "origin/main:docs/plan-2026-09-open-issues.md:79"],
     "trigger": "1 (reached released versions)", "owner_seat": "R9-EG-B8 fixer (fixer.md)", "status": "not-started"},
    {"subject": "#1736 RCA (EG-B0)", "where": [f"{AR}/ALT-ROSTER.json R9-EG-B0", f"{FP}:.claude/workflows/wave-r9-groups.json R9-EG-B0",
                                              "origin/main:docs/plan-2026-09-open-issues.md:69"],
     "trigger": "1 + cross-round class", "owner_seat": "root-cause seat EG-B0",
     "status": "done (RCA-1736 on #1736 at 19:47Z); both rosters still show EG-B0 not-started; fixplan commit 27049219 set 'rca-done' on EG-B1 instead"},
    {"subject": "RCA-1736 countermeasures: EG-B1 per-solve immutable inputs; fold class into bugclasses.json; cross-round barrier-window policy",
     "where": [f"{FP}:.claude/workflows/wave-r9-groups.json R9-EG-B1", "RCA-1736.md §5"], "trigger": "from RCA",
     "owner_seat": "EG-B1 fixer; policy to tvofi", "status": "not-started (EG-B1 wave 12)"},
    {"subject": "F11.5: land the RCA seats' approved policy drafts A1-A9 (fixer.md, root-cause.md, D1.md, tests/README.md, defect-root-cause.md)",
     "where": [f"{FP}:handoff/round9/FIX-PLAN.md §5/§10", f"{AR}/ALT-ROSTER.json R9-F11.5"], "trigger": "from 14 class RCAs",
     "owner_seat": "F11.5 fixer (sonnet)", "status": "not-started"},
] + [
    {"subject": f"class barrier {c} from its RCA prototype", "where": [f"{FP}:.claude/workflows/wave-r9-groups.json {g}", f"{AR}/ALT-ROSTER.json {g}"],
     "trigger": "class (N>=3)", "owner_seat": f"{g} fixer", "status": "not-started"}
    for c, g in [("P1", "R9-F1.6"), ("P3", "R9-F1.10"), ("P2 + P6", "R9-F1.11"), ("P9", "R9-F6.3"),
                 ("N-solve-recompute + N-cpu-gate-blind", "R9-F10.2"), ("I1", "R9-F10.3"), ("I5 (doc_claims arms)", "R9-F10.4"),
                 ("I4", "R9-F11.4")]
] + [
    {"subject": "#1721 policy-docs/env-matrix/pr-contract red on main (Actions-token ruleset view): cheaper detector 'owed to a root-cause seat'",
     "where": [f"{R}/pull/1721 (## Red checks)"], "trigger": "2 (red on main)", "owner_seat": "unassigned root-cause seat",
     "status": "no RCA found"},
    {"subject": "#1545 root-cause seat (weigh the typing arm)", "where": ["origin/main:.claude/workflows/wave-r8-groups.json R8-I5a", f"{R}/pull/1590"],
     "trigger": "plan §6 (round 8)", "owner_seat": "root-cause seat beside R8-I5a", "status": "no RCA found (#1545 has 0 comments)"},
    {"subject": "#1070 ratchet-budgets corpus-cap headroom", "where": ["origin/main:docs/plan-2026-09-open-issues.md:1302"],
     "trigger": "recurring friction", "owner_seat": "root-cause seat 'in flight' (2026-09-17)", "status": "no RCA found"},
    {"subject": "v6.6.0 options-flow freeze of the whole HA instance (owner CRITICAL report)",
     "where": [f"{R}/issues/201#issuecomment-5712963862", "origin/main:docs/delivery/1107.md"], "trigger": "1 (release)",
     "owner_seat": "fix/options-flow-freeze seat", "status": "no RCA found; #1107 'not shown to fix that freeze'"},
    {"subject": "#1041 silent-zero: cost-test re-run owed before its refusals are cited as settled",
     "where": [f"{R}/issues/1041#issuecomment-5693870772", f"{R}/issues/1041#issuecomment-5694083243"],
     "trigger": "class (4 post-analysis sightings)", "owner_seat": "root-cause seat", "status": "not done"},
    {"subject": "P1 residue (bounded out-of-domain values, blast radius) and P11 residual D6-s1-81: tvofi ruling",
     "where": [f"{PLAN9}/p1/RCA.md", f"{PLAN9}/p11/RCA.md", "origin/main:tools/audit/bugclasses.json P11"],
     "trigger": "class barrier bound", "owner_seat": "tvofi", "status": "asked"},
    {"subject": "PR-body red at a superseded head (#1116, #1121): RCA at the third instance",
     "where": ["origin/main:docs/HANDOVER.md (~line 655)"], "trigger": "recurring (conditional, at 3)", "owner_seat": "root-cause seat",
     "status": "armed, not triggered"},
    {"subject": "recurring ledger classes with no RCA: P4 (14 historical, N=1 in r9), I2 (5 of 6 rounds), P7 (4 of 6 rounds; barriered by F1.1 without RCA), P8 (N=2)",
     "where": [f"{FP}:handoff/round9/FIX-PLAN.md §9 lines ~290-300", "origin/main:tools/audit/bugclasses.json"],
     "trigger": "cross-round recurrence (no per-round trigger)", "owner_seat": "ledger owner (unassigned)", "status": "flagged only"},
]
json.dump(sched, open(os.path.join(OUT, "rca_scheduled.json"), "w"), indent=1, ensure_ascii=False)

from collections import Counter
print(len(rows), Counter(r["status"] for r in rows), len(sched))
print("undocumented:", [r["id"] for r in rows if not r["documented_in_register"] and not r["documented_on_issue"]["value"]])
print("unlanded:", [r["id"] for r in rows if r["status"] == "prototype-only"])
