#!/usr/bin/env python
"""Emit tools/audit/round2/QUIET.md from quiet.json (tables generated, never typed)."""
import json, os
RND = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
d = json.load(open(os.path.join(RND, "quiet.json")))
rows, d3 = d["retaken"], d["d3_confirmed"]

def num(v):
    if v is None: return "-"
    if isinstance(v, list): return f"{v[0]:g}-{v[1]:g}"
    if isinstance(v, float):
        if v == int(v): return f"{int(v)}"
        return f"{v:.6g}"
    return str(v)

def mark(r):
    return {True: "yes", False: "**NO**", None: "n/a"}[r["reproduced"]]

HARNESS_ORDER = []
for r in rows:
    key = (r["id"], r["harness"], r["log"])
    if key not in HARNESS_ORDER: HARNESS_ORDER.append(key)

out = []
w = out.append
w("# Quiet-window re-takes and D3 full-gate confirmations (round 2)")
w("")
w("Baseline `c398fc84eec25fc44b60d74aae05b9a2da205884` throughout. Interpreter")
w("`/Users/timmalmstrom/copilot-worktrees/heatpump_optimizer/tvofi-claude/.venv/bin/python`,")
w("`PYTHONPATH=tests/hastub`, the five thread-pin variables exported before any numpy")
w("import, every harness run from the worktree or export it was written in. The gate")
w("lock `/tmp/hpo-gate.lock` was held for the whole window.")
w("")
w("## Conditions, and one caveat about `load1` on this box")
w("")
w("The box was idle: no other auditor's process ran during the window (`ps` showed no")
w("Python or Node but my own; `top` reported **92-96 % idle CPU** before every run).")
w("But **`load1` never fell below 1.38**: this Mac carries a standing load average of")
w("roughly 1.4-2.0 from system daemons that are not CPU-bound, so the contract's")
w("`load1 <= 1.5` gate is not reachable here even on a completely idle machine. Each")
w("run was therefore started at a `load1` trough *and* at >85 % idle CPU, and both")
w("numbers are recorded in every log (`QUIET_LOAD_BEFORE`, `QUIET_CPU_BEFORE`,")
w("`QUIET_LOAD_AFTER`, `QUIET_CPU_AFTER`) alongside the harness's own closing")
w("`RESULT load1`. `thread_factor` was 1.000 on every numpy harness.")
w("")
w("Two runs were redone because they were taken while the box was busy:")
w("")
w("- `D9-h4.log` (load1 3.54) -> **`D9-h4-redo.log`** (load1 2.20 -> 1.93). The redo is canonical.")
w("- `D9-h3-run2/run3` were caught by a load spike (load1 15.8 and 8.0 at start, though")
w("  CPU was 95 % idle). **`D9-h3-run4.log`** (load1 1.47 -> 1.42, the only sample inside")
w("  the contract's gate at both ends) is canonical for D9-05; all four samples agree.")
w("")
w(f"## Part 1 - re-takes ({len(rows)} numbers, {sum(1 for r in rows if r['reproduced'] is True)} reproduced, "
  f"{sum(1 for r in rows if r['reproduced'] is False)} not)")
w("")
w("`reproduced` applies the tolerance the finder's report states (timing +-25 % unless")
w("the report is tighter). Full machine-readable detail in `quiet.json`.")
w("")
for fid, harness, log in HARNESS_ORDER:
    sub = [r for r in rows if (r["id"], r["harness"], r["log"]) == (fid, harness, log)]
    r0 = sub[0]
    w(f"### {fid} - `{harness}`")
    w("")
    w(f"Command: `OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 "
      f"VECLIB_MAXIMUM_THREADS=1 PYTHONPATH=tests/hastub <interp> {harness}`  ")
    w(f"Log: `{log}` - load1 {num(r0['load1'])}, thread_factor {num(r0['thread_factor'])}, swapins {num(r0['swapins'])}")
    w("")
    w("| metric | original (fan-out) | quiet | tol | reproduced | note |")
    w("|---|---|---|---|---|---|")
    for r in sub:
        w(f"| `{r['metric']}` | {num(r['original'])} | {num(r['quiet'])} | {r['tolerance']} | {mark(r)} | {r['note']} |")
    w("")

w("### What did not reproduce, and what it means")
w("")
w("Four classes, none of which weakens the finding it belongs to:")
w("")
w("1. **Absolute CPU/wall figures are 26-49 % lower on the quiet box** (D9-01's five")
w("   `solve_cpu` values, D9-03's memo arm, D9's `executor_cpu`, D0-02's")
w("   `production_cpu_total` 111.8 -> 80.3 s, D10-14's `wall_s` 1818 -> 982 s). Every one")
w("   moves in the expected direction - the fan-out numbers were inflated by ten")
w("   auditors sharing the box - and every *ratio* against `reference_solve` reproduced")
w("   inside tolerance. This is exactly the split the harness contract predicts, and it")
w("   is why the ratios, not the milliseconds, carry the findings.")
w("")
w("2. **D9-05's gap distribution is worse than reported, not better.** The starvation")
w("   share - the number the finding rests on - reproduced (0.967 -> 0.942-0.950 across")
w("   four samples, inside the report's +-5 %). But the *longest GIL hold* came out")
w("   **265 / 313 / 376 / 412 ms** against a reported 39.4 ms (report range 39-75 ms),")
w("   with `gap_p99` 232-338 ms against 35.8 ms, and `gap_p50` *lower* (1.6-2.4 ms vs")
w("   13.3 ms). The stage attribution also differs: the longest hold landed in")
w("   `dhw_lp_build` in three samples and `batch_sim` in the fourth, where the report")
w("   names `simulate_trajectory_batch`. Under contention the loop was being scheduled")
w("   often enough to break long holds into many medium ones; on an idle box the")
w("   executor thread keeps the GIL for a quarter to two-fifths of a second at a")
w("   stretch. **D9-05 understates its own defect** and should be re-stated from these")
w("   numbers, with the LP build named alongside the batch simulation.")
w("")
w("3. **D1-02's lazy arm halved: 6 -> 3 zombie service calls**, and the actuation flipped")
w("   from `switch.turn_on` to `switch.turn_off` in both arms. The finding's headline")
w("   (the eager arm: 3 calls, 1 actuation, 2 store writes) reproduced exactly, as did")
w("   every `notready_*` count. The lazy arm ran one zombie cycle here rather than two;")
w("   the direction of the switch command follows the plan the frozen clock lands on,")
w("   and neither is load-related. The claim stands; the `6` in the report's tolerance")
w("   line does not.")
w("")
w("4. **D0-02's wall/CPU only.** All 160 cells were compared field by field against the")
w("   fan-out run's `out/race_grid_24h_baseline.json`: **every one of 22 numeric fields")
w("   in all 160 cells was bit-identical** (max |delta| 0.0), including every SEK gap,")
w("   projected gradient and iteration count. The solver is deterministic on this build.")
w("")
w("5. **D10-14\'s coverage percentage is stable; only its wall time moved.**")
w("   `coverage_total_pct` came back at exactly 88.4 %, `config_flow.py` at 86.4 %,")
w("   12877 statements and 20 of 45 modules at 95 % - all identical. `coverage_missing`")
w("   moved 1493 -> 1491, and a diff of the per-module tables shows the whole difference")
w("   is `sysid.py` (90.4 % -> 91.4 %, two lines): a fixture-dependent branch, which is")
w("   the caveat the finder already stated. The same two scripts exited non-zero")
w("   (`entities.py` on the export\'s missing RELEASE_NOTES.md, `golden.py` on the")
w("   strict comparison this box cannot reproduce), so the measured set is unchanged.")
w("")
w("## Part 2 - D3 full-gate confirmations")
w("")
w("Each mutant, in order, in `/Users/timmalmstrom/copilot-worktrees/heatpump_optimizer/audit-r2-D3`:")
w("")
w("```")
w("git checkout -q -b quiet-<id> c398fc84eec25fc44b60d74aae05b9a2da205884")
w("git apply tools/audit/round2/D3/mutants/<id>.patch")
w("git commit -qam 'quiet-window mutant <id>'      # env_drift refuses HEAD == baseline")
w("PYTHON=<interp> GATE_SCOPE=full GOLDEN_MODE=drift \\")
w("  GOLDEN_REF=c398fc84eec25fc44b60d74aae05b9a2da205884 GATE_JOBS=1 ./tests/run.sh")
w("git checkout -q --detach c398fc84eec25fc44b60d74aae05b9a2da205884 && git branch -D quiet-<id>")
w("```")
w("")
w("Driver: `tools/audit/round2/quiet/d3_gate.sh <id>` (asserts the preconditions, runs")
w("the gate, restores the worktree, prints the verdict).")
w("")
w("| mutant | finding | patch | verdict | killed by | scripts run | wall | log |")
w("|---|---|---|---|---|---|---|---|")
for r in d3:
    v = "**SURVIVED**" if r["survived"] else "killed"
    kb = ", ".join(r["killed_by"]) if r["killed_by"] else "-"
    w(f"| {r['mutant']} | {r['finding']} | `tools/audit/round2/D3/mutants/{r['mutant']}.patch` | {v} | {kb} "
      f"| {r['scripts_run']} | {r['wall_s']} s | `{r['log']}` |")
w("")
w("**All six survive the full gate: six confirmed suite gaps.** Each run ended in")
w("`ALL TEST SCRIPTS PASSED` with 16 scripts executed, nothing scoped out, and the")
w("mutant provably in the tree (`git diff --stat` against the baseline is recorded as")
w("`D3_HEAD` in each log).")
w("")
w("This closes the gap D3's own prescreen left open: the prescreen could not run")
w("`stress.py`, `edge.py` or `backtest.py`, and skipped `golden.py` because its strict")
w("comparison does not reproduce on this box. All three now ran, plus `env_drift.py")
w("--all` against the baseline (the drift-mode replacement for `golden.py`) and")
w("`card_drift.mjs`. The survivors survived those too.")
w("")
w("Scope caveat, stated once: this is the gate CI runs on **every push and PR**, which")
w("skips `tests/rolling.py` (`SLOW=1`, the closed-loop simulation) - the same skip CI's")
w("fast lane takes. CI's nightly/dispatch job sets `SLOW=1`")
w("(`.github/workflows/tests.yml:293`), so a mutant only `rolling.py` could catch would")
w("still show as a survivor here. `golden.py` is skipped in drift mode by design.")
w("")
w("## Worktree hygiene")
w("")
w("`audit-r2-D3` ends at `c398fc84eec25fc44b60d74aae05b9a2da205884` detached, no")
w("`quiet-*` branch, `git status` showing only `?? tools/audit/`, and `git diff")
w("--stat baseline HEAD` empty. `audit-r2-D0`'s `out/race_grid_24h_baseline.json` was")
w("overwritten by the re-take and has been restored to the fan-out original; the quiet")
w("copy is kept beside the logs as `D0-race_grid_24h_baseline.quiet.json`. Production")
w("and tests were never modified outside D3's apply/revert cycle.")
w("")
w("## Files")
w("")
w("- `tools/audit/round2/quiet.json` - machine-readable, both parts")
w("- `tools/audit/round2/quiet/*.log` - one log per run, each carrying its own conditions")
w("- `tools/audit/round2/quiet/run_quiet.sh`, `d3_gate.sh` - the two drivers")
w("- `tools/audit/round2/quiet/emit.py`, `emit_md.py` - build `quiet.json` and this file from the logs")
open(os.path.join(RND, "QUIET.md"), "w").write("\n".join(out) + "\n")
print("wrote QUIET.md:", len(out), "lines")
