#!/usr/bin/env python3
"""The next-session prompt, generated from the resume doc and the roster.

    python3 tools/audit/seat/handover_prompt.py [--repo OWNER/REPO] \
        [--roster-ref GITREF | --roster-file PATH] [--resume FILE] \
        [--out PATH]
    python3 tools/audit/seat/handover_prompt.py --self-test \
        [--roster-file R] [--resume S]

A handover prompt hand-written at the end of a session is stale before the
next one reads it; this regenerates the structural parts from the two live
sources. The shape is the recorded startup shape:

  Read first     -- the rules-first pointer: CLAUDE.md, the .claude/rules/
                    file each task touches, the seat brief.
  Load the state -- the fetch and worktree commands for every IN-FLIGHT group
                    (a resume.stage that is neither not-started nor done),
                    generated from the roster's resume fields, plus the resume
                    doc's path and the ready-next groups (from the doc when
                    --resume is given, else recomputed from the roster).
  Resume steps   -- what a seat does before it works.
  Identity       -- the authoring and merge rules, generated from the roster
                    (repo, session, fork base, per-role model routing).
  Done criteria  -- what closing the round means, from the roster's own
                    fields.

`--self-test` renders from a fixture roster and fixture resume text.
"""

from __future__ import annotations

import argparse
import datetime
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import roster_lib  # noqa: E402

SELF = "tools/audit/seat/handover_prompt.py"
NOT_STARTED = "not-started"


def ready_next(roster: dict) -> list:
    open_ = roster_lib.open_groups(roster)
    depth = roster_lib.depth_of(roster)
    return sorted((depth[g], g) for g, gr in open_.items()
                  if all(a not in open_ for a in gr.get("after") or []))


def in_flight(roster: dict) -> list:
    out = []
    for g, gr in roster_lib.groups_of(roster).items():
        stage = (gr.get("resume") or {}).get("stage") or NOT_STARTED
        if stage not in roster_lib.DONE_STAGES and stage != NOT_STARTED:
            out.append((g, gr))
    return out


def _ready_from_doc(text: str) -> list:
    sec = re.search(r"## Ready next\n(.*?)(?:\n## |\Z)", text, re.S)
    if not sec:
        return []
    return re.findall(r"^- (R9-\S+)", sec.group(1), re.M)


def render(roster: dict, source: str, resume_path: str, resume_text: str,
           date: str) -> str:
    repo = roster.get("repo") or "<repo>"
    session = roster.get("session") or "<session>"
    L = [f"# Next-session prompt ({source})",
         f"Generated by `{SELF}` {date}; roster {source}.", "",
         "## Read first (rules, before any work)", "",
         "`CLAUDE.md` at the checkout root -- the index: every policy file and "
         "the obligation each carries. Then the `.claude/rules/` file each "
         "task touches, loaded when it binds. Then the seat brief your work "
         "names under `tools/audit/briefs/` (the fixer's is `fixer.md`). "
         "Call the owner tvofi.", "",
         "## Load the state", "",
         "```bash",
         "git fetch origin",
         f"git show {source}:{roster_lib.ROSTER_PATH}   # the roster",
         "```"]
    inflight = in_flight(roster)
    if inflight:
        L += ["", "Worktrees in flight (a crashed seat restarts from its "
                  "branch and note, never from scratch):"]
        for g, gr in inflight:
            r = gr.get("resume") or {}
            L += [f"- {g} (stage {r.get('stage')}, branch `{r.get('branch')}`, "
                  f"note `{r.get('note_file')}`): `git fetch origin "
                  f"{r.get('branch')} && git worktree add --detach "
                  f"$SEAT/wt FETCH_HEAD`; read the note file and check its "
                  f"commit equals the fetched head"]
    ready = (_ready_from_doc(resume_text) if resume_text else
             [g for _, g in ready_next(roster)])
    if resume_path:
        L += ["", f"Resume doc: `{resume_path}` -- its Roster section is the "
                  f"counters; do not re-derive them by hand."]
    L += ["", "Ready next (after-edges satisfied; nothing open constrains "
              "them): " + (", ".join(ready) or "none.")]
    L += ["", "## Resume steps", "",
          "1. Read the resume doc's Roster and Ready next sections.",
          "2. Claim one ready group and announce it on the tracking issue "
          "#201 before opening work -- before each PR, merge and release, "
          "not only after a state change.",
          "3. Work at your own merge base; re-derive every figure you quote "
          "there. A figure from another seat's run is a claim, not a "
          "measurement.",
          "", "## Identity and merge (from the roster)", "",
          f"- repo `{repo}`, session `{session}`"
          + (f", fork base `{roster['fork']}` at plan time"
             if roster.get("fork") else "") + ".",
          "- Pull requests are authored by the `hpo-author` App via "
          "`tools/audit/seat/app_push.sh` (never `push.sh`, never tvofi); "
          "`hpo-approver` approves non-code-owned PRs; only tvofi reviews "
          "code-owned paths (decision 0011).",
          "- Model routing per group is the roster's own fields "
          "(`fixerModel`, `reviewerModel`, `effort`); route by judgement, "
          "never by default.",
          "- Never stamp from a wave seat: versions are assigned by "
          "`tools/release/stamp.py` after the merge.",
          "", "## Done criteria", "",
          "- every roster group's `resume.stage` is `done` or `rca-done`;",
          "- every issue in `issues[]` is closed by the PR the roster makes "
          "its closer (`fixes[]`), read back on GitHub, not assumed;",
          "- CI green at each merged head and the delivery row written "
          "(`docs/delivery/<N>.md`);",
          "- the resume doc regenerated under its budget "
          "(`tools/audit/seat/resume_doc.py`) and the plan table with it "
          f"(`{Path(SELF).parent / 'plan_table.py'}`).",
          ""]
    return "\n".join(L)


def main(argv=None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--repo", default="tvofi/heatpump_optimizer")
    src = p.add_mutually_exclusive_group()
    src.add_argument("--roster-ref", default="handoff/audit-r9-fixplan")
    src.add_argument("--roster-file")
    p.add_argument("--resume")
    p.add_argument("--out")
    p.add_argument("--self-test", action="store_true")
    a = p.parse_args(argv)
    if a.self_test:
        return _self_test()
    roster = (roster_lib.load_roster_file(a.roster_file) if a.roster_file
              else roster_lib.show_roster(a.repo, a.roster_ref))
    source = a.roster_file or a.roster_ref
    rtext = Path(a.resume).read_text(encoding="utf-8") if a.resume else ""
    today = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    text = render(roster, source, a.resume, rtext, today)
    if a.out:
        Path(a.out).write_text(text, encoding="utf-8")
        print(f"wrote {a.out}")
    else:
        sys.stdout.write(text)
    return 0


# ------------------------------------------------------------------ self-test
def _fixture_roster() -> dict:
    def g(gid, lane, after, stage):
        return {"group": gid, "lane": lane, "issues": [10], "fixes": [],
                "after": after, "brief": f"fixture {gid}",
                "fixerModel": "sonnet", "reviewerModel": "opus",
                "resume": {"stage": stage, "branch": f"handoff/{gid.lower()}",
                           "note_file": f"handoff/round9/fix/resume/{gid}.md"}}
    return {"repo": "fixture/roster", "session": "fixture-r9", "fork": "db878b29",
            "groups": [
        g("R9-A", "L1", [], "done"),
        g("R9-B", "L1", ["R9-A"], "in-review"),
        g("R9-C", "L2", [], "not-started"),
    ]}


def _self_test() -> int:
    failed = []
    n_checks = [0]

    def check(name, ok, got=""):
        n_checks[0] += 1
        if not ok:
            failed.append(f"{name} (got: {got})")

    roster = _fixture_roster()
    resume = ("# Resume (fixture)\n\n## Ready next\n\n"
              "- R9-C (wave 1, 0 satisfied edge(s))\n\n## Traps\n\nnone\n")

    text = render(roster, "fixture", "handoff/x/RESUME.md", resume, "2026-10-04")
    check("rules-first pointer", "Read first" in text and "CLAUDE.md" in text
          and "tvofi" in text)
    check("state load commands", "git fetch origin" in text
          and f"git show fixture:{roster_lib.ROSTER_PATH}" in text)
    # in-flight: B (in-review) generates a pickup command; not-started C and
    # done A do not.
    check("in-flight pickup command", "git fetch origin handoff/r9-b" in text
          and "handoff/round9/fix/resume/R9-B.md" in text)
    check("not-started group has no pickup", "handoff/r9-c" not in text)
    check("done group has no pickup", "handoff/r9-a" not in text)
    # ready-next taken from the resume doc when given.
    check("ready from resume doc", "Ready next" in text
          and "R9-C" in text[text.find("Ready next"):])
    doc_free = render(roster, "fixture", "", "", "2026-10-04")
    check("ready recomputed without doc",
          "- R9-C" in doc_free or "R9-C" in doc_free)
    # identity generated from the roster.
    check("identity from roster", "repo `fixture/roster`" in text
          and "session `fixture-r9`" in text and "`db878b29`" in text)
    check("merge identity", "hpo-author" in text and "hpo-approver" in text
          and "tvofi reviews" in text and "decision 0011" in text)
    check("done criteria", "resume.stage" in text and "docs/delivery/" in text)
    check("resume steps", "Claim one ready group" in text
          and "#201" in text)

    # empty roster: no in-flight block, ready-next says none.
    empty = render({"groups": [], "repo": "r"}, "fixture", "", "",
                   "2026-10-04")
    check("empty roster renders", "Ready next" in empty
          and "none" in empty and "Worktrees in flight" not in empty)

    print(f"handover_prompt self-test: {n_checks[0]} checks, "
          f"{len(failed)} failed")
    for f in failed:
        print("FAIL", f)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
