#!/usr/bin/env python3
"""The resume markdown, regenerated from a roster and live pull-request state.

    python3 tools/audit/seat/resume_doc.py [--repo OWNER/REPO] \
        [--roster-ref GITREF | --roster-file PATH] [--out PATH] \
        [--traps FILE] [--budget-bytes N]
    python3 tools/audit/seat/resume_doc.py --offline --roster-file R \
        --pr-state S --self-test

Stateless: the roster arrives through --roster-ref (`git show`) or
--roster-file, the pull-request rows through `gh pr list --json` at run time
or through --pr-state (a fixture, with --offline, so the self-test needs no
network and no `gh`). A resume doc that a session hand-writes drifts from the
roster it summarizes; this regenerates the factual sections instead:

  Roster      -- counters: total, open, done, per-stage counts, wave count.
  Pull requests -- every open PR of the repo: number, head branch, state.
  Ready next  -- open groups whose after-edges are ALL done (or absent), so
                 nothing open still constrains them; ordered by wave.
  Traps       -- the --traps file appended verbatim (a trap is recorded once,
                 by whoever hit it; this section never paraphrases it).

THE BUDGET. The generated document is refused (--out not written, exit 1) if
it exceeds --budget-bytes (default 10240): a resume over its budget is the
signal to archive, not to keep growing it.

`--self-test` renders from a fixture roster and fixture PR state and checks
the counters, the PR rows, ready-next membership and ordering, the verbatim
trap append, and the budget refusal.
"""

from __future__ import annotations

import argparse
import datetime
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import roster_lib  # noqa: E402

SELF = "tools/audit/seat/resume_doc.py"
DEFAULT_BUDGET = 10240


def gh_open_prs(repo: str) -> list:
    out = subprocess.run(
        ["gh", "pr", "list", "--repo", repo, "--state", "open", "--json",
         "number,headRefName,state"],
        capture_output=True, text=True)
    if out.returncode != 0:
        raise RuntimeError(f"gh pr list failed: {out.stderr.strip()[:200]}")
    return [{"number": p["number"], "head": p["headRefName"],
             "state": p["state"]} for p in json.loads(out.stdout)]


def render(roster: dict, source: str, prs: list, traps: str) -> str:
    G = roster_lib.groups_of(roster)
    open_ = roster_lib.open_groups(roster)
    done = {k for k in G if k not in open_}
    stages: dict = {}
    for g in G.values():
        s = (g.get("resume") or {}).get("stage") or "?"
        stages[s] = stages.get(s, 0) + 1
    depth = roster_lib.depth_of(roster)
    open_waves = {depth[g] for g in open_}
    today = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    L = [f"# Resume ({source})",
         f"Generated by `{SELF}` {today}; roster {source}.", "",
         "## Roster", "",
         f"- groups: {len(G)} total, {len(open_)} open, {len(done)} done",
         "- stages: " + ", ".join(f"{k} {v}" for k, v in sorted(stages.items())),
         f"- open waves: {len(open_waves)} "
         f"(depths {', '.join(str(w) for w in sorted(open_waves)) or '-'})", "",
         "## Open pull requests", "",
         "| # | head | state |", "|---|---|---|"]
    L += [f"| #{p['number']} | {str(p['head']).replace('|', '/')} | "
          f"{p['state']} |" for p in prs] or ["| - | - | no open pull requests |"]
    ready = []
    for g, gr in open_.items():
        deps = gr.get("after") or []
        if all(a not in open_ for a in deps):
            ready.append((depth[g], g, len(deps)))
    L += ["", "## Ready next", "",
          "Open groups whose after-edges are all done (or absent); "
          "wave-ordered:", ""]
    L += [f"- {g} (wave {w}, {n} satisfied edge(s))"
          for w, g, n in sorted(ready)] or ["- none: every open group waits "
                                            "on another open group"]
    if traps:
        L += ["", "## Traps", "", traps.rstrip("\n"), ""]
    return "\n".join(L) + "\n"


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--repo", default="tvofi/heatpump_optimizer")
    src = p.add_mutually_exclusive_group()
    src.add_argument("--roster-ref", default="handoff/audit-r9-fixplan")
    src.add_argument("--roster-file")
    p.add_argument("--out")
    p.add_argument("--traps")
    p.add_argument("--budget-bytes", type=int, default=DEFAULT_BUDGET)
    p.add_argument("--offline", action="store_true",
                   help="use --pr-state instead of gh; no network")
    p.add_argument("--pr-state")
    p.add_argument("--self-test", action="store_true")
    a = p.parse_args(argv)
    if a.self_test:
        return _self_test()
    roster = (roster_lib.load_roster_file(a.roster_file) if a.roster_file
              else roster_lib.show_roster(a.repo, a.roster_ref))
    source = a.roster_file or a.roster_ref
    if a.offline:
        if not a.pr_state:
            print("resume_doc: --offline needs --pr-state", file=sys.stderr)
            return 2
        prs = json.loads(Path(a.pr_state).read_text(encoding="utf-8"))
    else:
        prs = gh_open_prs(a.repo)
    traps = Path(a.traps).read_text(encoding="utf-8") if a.traps else ""
    text = render(roster, source, prs, traps)
    size = len(text.encode())
    if size > a.budget_bytes:
        print(f"resume_doc: REFUSED: {size} bytes over the "
              f"{a.budget_bytes}-byte budget; archive before regenerating, "
              f"--out not written", file=sys.stderr)
        return 1
    if a.out:
        Path(a.out).write_text(text, encoding="utf-8")
        print(f"wrote {a.out} ({size} bytes of the {a.budget_bytes}-byte "
              f"budget)")
    else:
        sys.stdout.write(text)
    return 0


# ------------------------------------------------------------------ self-test
def _fixture_roster() -> dict:
    def g(gid, lane, after, stage):
        return {"group": gid, "lane": lane, "issues": [], "fixes": [],
                "after": after, "brief": f"fixture {gid}",
                "resume": {"stage": stage, "branch": f"handoff/{gid.lower()}"}}
    return {"repo": "fixture/roster", "groups": [
        g("R9-A", "L1", [], "done"),
        g("R9-B", "L1", ["R9-A"], "in-progress"),
        g("R9-C", "L2", ["R9-A"], "not-started"),
        g("R9-D", "L2", ["R9-B", "R9-C"], "not-started"),
        g("R9-E", "L1", ["R9-B"], "rca-done"),
        # mixed edges: one done dep (A), one open dep (D). Only the `all`
        # reading keeps it out of ready-next; an `any` mutant makes it ready.
        g("R9-F", "L2", ["R9-A", "R9-D"], "not-started"),
    ]}


def _self_test() -> int:
    failed = []
    n_checks = [0]

    def check(name, ok, got=""):
        n_checks[0] += 1
        if not ok:
            failed.append(f"{name} (got: {got})")

    roster = _fixture_roster()
    prs = [{"number": 1946, "head": "fix/r9-fr-8", "state": "OPEN"},
           {"number": 1940, "head": "fix|/odd", "state": "OPEN"}]
    traps = "TRAP one: never re-derive the wave math by hand.\n"
    text = render(roster, "fixture", prs, traps)

    # counters: 6 total, 4 open, 2 done; stage census; 3 open waves.
    check("total/open/done", "groups: 6 total, 4 open, 2 done" in text)
    # the census is by recorded stage value; rca-done is a done stage for the
    # open/done split but its own stage name here.
    check("stage census",
          "stages: done 1, in-progress 1, not-started 3, rca-done 1" in text,
          text[text.find("stages:"):text.find("stages:") + 70])
    # open depths: B and C's only edge (A) is done, so both are wave 1;
    # D 2; F (mixed edges) 3.
    check("open waves", "open waves: 3 (depths 1, 2, 3)" in text)

    # PR rows, pipe-safe.
    check("pr row", "| #1946 | fix/r9-fr-8 | OPEN |" in text)
    check("pr row pipe-safe", "| #1940 | fix//odd | OPEN |" in text)

    # ready-next: B and C's edges are all done, D waits on open B and C, and
    # F has a MIXED edge set (one done, one open) and must stay out.
    ready = text[text.find("## Ready next"):]
    check("ready has B", "- R9-B (wave 1, 1 satisfied edge(s))" in ready, ready)
    check("ready has C", "- R9-C (wave 1, 1 satisfied edge(s))" in ready, ready)
    check("ready ordered and excludes D and F",
          ready.find("R9-B") < ready.find("R9-C")
          and "R9-D" not in ready and "R9-F" not in ready)

    # traps verbatim.
    check("traps verbatim", "TRAP one: never re-derive the wave math by "
          "hand." in text and "## Traps" in text)

    # budget: a padded traps file refuses, and --out is not written.
    out = Path("/nonexistent-resume-doc-out")  # never written on refusal
    big_traps = "x" * 11000
    big = render(roster, "fixture", prs, big_traps)
    check("budget refusal size",
          len(big.encode()) > DEFAULT_BUDGET, len(big.encode()))
    # drive the refusal through main() so the flag path itself is pinned
    import tempfile
    d = tempfile.mkdtemp(prefix="hpo-fr8-resume-")
    rf, pf, tf = (Path(d, "r.json"), Path(d, "p.json"), Path(d, "t.txt"))
    rf.write_text(json.dumps(roster), encoding="utf-8")
    pf.write_text(json.dumps(prs), encoding="utf-8")
    tf.write_text(big_traps, encoding="utf-8")
    rc = main(["--offline", "--roster-file", str(rf), "--pr-state", str(pf),
               "--traps", str(tf), "--out", str(Path(d, "o.md"))])
    check("budget refusal rc", rc == 1, rc)
    check("budget refusal wrote nothing", not Path(d, "o.md").exists())

    # and the same render under budget writes.
    tf.write_text(traps, encoding="utf-8")
    rc = main(["--offline", "--roster-file", str(rf), "--pr-state", str(pf),
               "--traps", str(tf), "--out", str(Path(d, "o.md"))])
    check("under budget writes", rc == 0 and Path(d, "o.md").exists())

    # empty roster renders (a degenerate roster is still a document).
    empty = render({"groups": []}, "fixture", [], "")
    check("empty roster", "groups: 0 total, 0 open, 0 done" in empty
          and "no open pull requests" in empty)

    import shutil
    shutil.rmtree(d, ignore_errors=True)
    print(f"resume_doc self-test: {n_checks[0]} checks, {len(failed)} failed")
    for f in failed:
        print("FAIL", f)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
