#!/usr/bin/env python3
"""Measure the device pre-fill's fuzzy fallback over its labelled corpus.

W1067-G7b-3's fallback guesses, so its acceptance is not how many roles it
fills but that it fills none wrongly. That is a count over a labelled corpus,
and this script is the instrument:

    PYTHONPATH=tests/hastub python3 tools/measure_prefill_corpus.py

It prints, from ``tests/fixtures/prefill_corpus.json`` (generated by
``tools/gen_device_fixtures.py --write-corpus``):

* the per-role table -- how many roles the fallback suggested, how many were
  the corpus's label, how many were something else, and how many labelable
  roles it left alone. Precision is ``correct / suggested``, recall
  ``correct / (correct + wrong + missed)``: recall is reported, never gated,
  because a wrong suggestion costs a user a slot fed the wrong reading while a
  missed one costs a slot they fill by hand;
* how many roles the fallback fills on each corpus device, which is the table
  W1067-POST1 takes its qualifying minimum from;
* the threshold/margin grid, so the pair the module ships is the pair this
  measurement found rather than one chosen by feel; and
* the null control: the same run with the name scores forced to zero. The hard
  filter alone must suggest nothing, or the decision is not resting on the
  names at all.

Every number the pull request quotes comes from this one run.
"""
from __future__ import annotations

import json
import pathlib
import sys
from collections.abc import Callable, Iterable, Mapping
from typing import NamedTuple

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "custom_components"))

from heatpump_optimizer import device_prefill, name_match  # noqa: E402

FIXTURES = ROOT / "tests" / "fixtures"

#: The grid the shipped pair is chosen from. Coarse enough to read, fine
#: enough that the zero-wrong window's own edges are visible in the printout.
THRESHOLDS = (0.40, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80)
MARGINS = (0.00, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12)


class RoleRow(NamedTuple):
    """One role's column of the corpus table."""

    role: str
    suggested: int
    correct: int
    wrong: int
    missed: int

    @property
    def precision(self) -> float:
        return self.correct / self.suggested if self.suggested else 1.0

    @property
    def recall(self) -> float:
        labelable = self.correct + self.wrong + self.missed
        # No device in the corpus carries an entity for this role: there is
        # nothing to recall, which is not a miss.
        return self.correct / labelable if labelable else 1.0


class DeviceRow(NamedTuple):
    """One corpus device: what its table decided, and what the fallback added."""

    device: str
    platform: str
    hand_shaped: bool
    records: int
    tabled: int
    filled: int
    wrong: int


class Wrong(NamedTuple):
    """One wrong suggestion, named the way the pull request must name it."""

    device: str
    role: str
    label: str | None
    suggested: str


class Report(NamedTuple):
    """One measurement of the whole corpus."""

    roles: tuple[RoleRow, ...]
    devices: tuple[DeviceRow, ...]
    wrong: tuple[Wrong, ...]

    @property
    def correct(self) -> int:
        return sum(row.correct for row in self.roles)

    @property
    def missed(self) -> int:
        return sum(row.missed for row in self.roles)

    @property
    def suggested(self) -> int:
        return sum(row.suggested for row in self.roles)


def corpus() -> dict:
    """The recorded corpus. Generated, never hand-edited."""
    return json.loads((FIXTURES / "prefill_corpus.json").read_text(encoding="utf-8"))


def records(device: Mapping) -> list[device_prefill.EntityRecord]:
    """One corpus device's records as the module reads them."""
    return [
        device_prefill.EntityRecord(
            platform=row["platform"],
            unique_id=row["unique_id"],
            entity_id=row["entity_id"],
            original_name=row["original_name"],
            translation_key=row["translation_key"],
            device_class=row["device_class"],
            unit=row["unit"],
            state_class=row["state_class"],
        )
        for row in device["records"]
    ]


def _zero(name: str, phrase: str) -> float:
    """The null control's scorer: no name evidence at all."""
    return 0.0


def _filled(device: Mapping, score: Callable[[str, str], float] | None,
            threshold: float, margin: float) -> tuple[dict[str, str], dict[str, str]]:
    """``(tabled, filled)`` for one device: what each stage resolved.

    The table first, then the matcher over the roles it left empty -- the two
    steps ``device_prefill.resolve_with_fallback`` composes, driven here
    directly so the grid can vary the decision rule. That the two agree at the
    shipped pair is asserted in ``tests/features.py``.
    """
    own = records(device)
    tabled = device_prefill.resolve(own)
    hits = name_match.matches(
        own, taken=tabled, threshold=threshold, margin=margin, name_score=score,
    )
    return (
        {role: resolved.entity_ids[0] for role, resolved in tabled.items()},
        {hit.role: hit.entity_id for hit in hits},
    )


def measure(threshold: float = name_match.THRESHOLD,
            margin: float = name_match.MARGIN,
            zero_names: bool = False) -> Report:
    """The corpus measured at one decision rule."""
    score = _zero if zero_names else None
    counts = {role: [0, 0, 0, 0] for role in name_match.ROLE_FILTERS}
    devices, wrong = [], []
    for device in corpus()["devices"]:
        tabled, filled = _filled(device, score, threshold, margin)
        labels = device["labels"]
        for role in name_match.ROLE_FILTERS:
            if role in tabled:
                continue
            got = filled.get(role)
            if got is None:
                if labels[role] is not None:
                    counts[role][3] += 1
                continue
            counts[role][0] += 1
            if labels[role] == got:
                counts[role][1] += 1
            else:
                counts[role][2] += 1
                wrong.append(Wrong(device["name"], role, labels[role], got))
        devices.append(DeviceRow(
            device["name"], device["platform"], device["hand_shaped"],
            len(device["records"]), len(tabled), len(filled),
            sum(1 for row in wrong if row.device == device["name"]),
        ))
    return Report(
        tuple(
            RoleRow(role, *counts[role]) for role in sorted(name_match.ROLE_FILTERS)
        ),
        tuple(devices),
        tuple(wrong),
    )


def grid() -> list[tuple[float, float, Report]]:
    """Every cell of the threshold/margin grid, measured."""
    return [
        (threshold, margin, measure(threshold, margin))
        for threshold in THRESHOLDS
        for margin in MARGINS
    ]


def chosen(cells: Mapping[tuple[float, float], Report] | None = None
           ) -> tuple[float, float]:
    """The pair the grid picks, by a rule that does not read like a feeling.

    Of the cells that suggest nothing wrongly, the ones that suggest as much
    *correctly* as any other; of those the deepest margin, and of those the
    lowest threshold. The margin comes first because it is what removes a
    near-tie -- two candidates the same words fit -- which is the one error
    the corpus can demonstrate; the threshold then sits at the knee of the
    curve the corpus is clean above, lower being better for the names it does
    not contain.
    """
    measured = cells if cells is not None else {
        (threshold, margin): measure(threshold, margin)
        for threshold in THRESHOLDS
        for margin in MARGINS
    }
    clean = [cell for cell, report in measured.items() if not report.wrong]
    if not clean:
        # No cell separates anything, which is itself a measurement: report
        # the least-bad cell so the caller's own assertion is what says so,
        # rather than dying here and hiding every check behind it.
        leanest = min(len(report.wrong) for report in measured.values())
        clean = [
            cell for cell, report in measured.items() if len(report.wrong) == leanest
        ]
    most = max(measured[cell].correct for cell in clean)
    kept = [cell for cell in clean if measured[cell].correct == most]
    deepest = max(cell[1] for cell in kept)
    return min(cell[0] for cell in kept if cell[1] == deepest), deepest


def _table(header: list[str], rows: Iterable[Iterable[str]]) -> None:
    cells = [[str(cell) for cell in row] for row in rows]
    widths = [
        max(len(line[index]) for line in [header, *cells])
        for index in range(len(header))
    ]
    for line in [header, *cells]:
        print("  ".join(
            cell.ljust(widths[index]) for index, cell in enumerate(line)
        ).rstrip())


def main(argv: list[str] | None = None) -> int:
    report = measure()
    print("== per role (the corpus, at the shipped decision rule) ==")
    _table(
        ["role", "suggested", "correct", "wrong", "missed", "precision", "recall"],
        [
            [row.role, row.suggested, row.correct, row.wrong, row.missed,
             f"{row.precision:.2f}", f"{row.recall:.2f}"]
            for row in report.roles
        ],
    )
    print(
        f"\ntotals: suggested {report.suggested}, correct {report.correct}, "
        f"WRONG {len(report.wrong)}, missed {report.missed}"
    )
    for row in report.wrong:
        print(f"  WRONG {row.device} {row.role}: label {row.label}, "
              f"suggested {row.suggested}")

    print("\n== roles the fallback fills per corpus device (W1067-POST1's table) ==")
    _table(
        ["device", "platform", "shape", "records", "tabled", "fallback", "wrong"],
        [
            [row.device, row.platform, "hand" if row.hand_shaped else "generated",
             row.records, row.tabled, row.filled, row.wrong]
            for row in report.devices
        ],
    )

    print(f"\n== threshold/margin grid ==\nTHRESHOLD = {name_match.THRESHOLD}, "
          f"MARGIN = {name_match.MARGIN} (the shipped pair, marked *)")
    cells = {
        (threshold, margin): measured for threshold, margin, measured in grid()
    }
    _table(
        ["threshold"] + [f"m={margin:.2f}" for margin in MARGINS],
        [
            [f"{threshold:.2f}"]
            + [
                f"{len(cells[(threshold, margin)].wrong)}"
                f"/{cells[(threshold, margin)].correct}"
                + ("*" if (threshold, margin)
                   == (name_match.THRESHOLD, name_match.MARGIN) else "")
                for margin in MARGINS
            ]
            for threshold in THRESHOLDS
        ],
    )
    print("cell = <wrong suggestions>/<correct suggestions> over the corpus")
    picked = chosen(cells)
    print(
        f"the grid picks threshold {picked[0]:.2f} at margin {picked[1]:.2f}; "
        f"the module ships {name_match.THRESHOLD:.2f} / {name_match.MARGIN:.2f}"
    )
    # What the two dials are each holding back, which is the whole argument
    # for shipping both: walk each axis down from the shipped pair until the
    # first cell that does suggest something wrongly, and name it.
    for label, axis, value in (
        ("threshold", THRESHOLDS, picked[0]),
        ("margin", MARGINS, picked[1]),
    ):
        lower = [step for step in axis if step < value]
        for step in reversed(lower):
            cell = (step, picked[1]) if label == "threshold" else (picked[0], step)
            edge = cells.get(cell)
            if edge is None:
                continue
            if edge.wrong:
                print(
                    f"the {label} axis gives its first wrong suggestion at "
                    f"{cell[0]:.2f}/{cell[1]:.2f}: "
                    + ";  ".join(
                        f"{row.device} {row.role} (label {row.label}) took "
                        f"{row.suggested}"
                        for row in edge.wrong
                    )
                )
                break
            print(f"the {label} axis at {cell[0]:.2f}/{cell[1]:.2f}: still clean, "
                  f"{edge.correct} correct")

    zilch = measure(zero_names=True)
    print(
        f"\n== null control: name scores zeroed ==\n"
        f"suggested {zilch.suggested}, wrong {len(zilch.wrong)}, "
        f"correct {zilch.correct} -- the hard filter alone suggests nothing: "
        f"{zilch.suggested == 0}"
    )
    return 0 if not report.wrong else 1


if __name__ == "__main__":
    sys.exit(main())
