#!/usr/bin/env python3
"""D7 round-5: is the production FIRST-ORDER sysid identifier biased on the
production two-state plant, and does the production adoption gate admit it?

Metric definition (one line): per building preset, the signed UA bias
(UA_fit - UA_true)/UA_true of (a) the one-state production fit
``sysid:SystemIdentification.identify`` and (b) the two-state production fit
``sysid:SystemIdentification.identify_slab``, both run on a step response
generated by the production plant ``thermal_model:ThermalModel`` with the
slab pair ``presets:derive`` assigns that preset; plus the boolean the
production gate ``sysid:slab_mode_identifiability`` returns for each preset.

Command:  PYTHONPATH=tests/hastub python3 tools/audit/round5/D7/sysid_first_order.py
Baseline SHA: 9bcb7352cabb43b413f5e3ca41b6dda4e1ac6d69
Machine: Apple M1, 8 GB (audit box)
Expected: identify() UA bias large in magnitude (>15 %) or refused; the
adoption gate (identifiability AND confidence>=0.3) refuses on every shipped
preset. Tolerance: bias exact to the run (deterministic, no RNG); the
protocol is fixed at SysIdConfig defaults.
Root rule: resolves the checkout from __file__ (Path(__file__).parents[5]),
so it must be run from the tree under test, not a tag worktree.
"""
from __future__ import annotations

import os

# toolkit thread pin, before numpy
for _p in (
    "OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
    "NUMEXPR_NUM_THREADS", "VECLIB_MAXIMUM_THREADS",
):
    os.environ.setdefault(_p, "1")

import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / "custom_components"))
PKG = ROOT / "custom_components" / "heatpump_optimizer"

from heatpump_optimizer import presets as P
from heatpump_optimizer import sysid
from heatpump_optimizer.thermal_model import (
    ThermalModel,
    ThermalParameters,
    ThermalState,
)

# The three shipped building presets, copied from tests/stress.py:BUILDINGS.
PRESETS = {
    "light_new": P.BuildingPreset(
        structure=P.STRUCTURE_TIMBER_CRAWLSPACE,
        era=P.ERA_POST_2005,
        heated_area_m2=120,
        lower_emitter=P.EMITTER_RADIATORS,
    ),
    "heavy_old": P.BuildingPreset(
        structure=P.STRUCTURE_MASONRY,
        era=P.ERA_PRE_1960,
        heated_area_m2=200,
        lower_emitter=P.EMITTER_FLOOR,
    ),
    "typical_slab": P.BuildingPreset(
        structure=P.STRUCTURE_CONCRETE_SLAB,
        era=P.ERA_1960_1980,
        heated_area_m2=150,
        lower_emitter=P.EMITTER_FLOOR,
    ),
}

OUTDOOR = 5.0        # within the sysid safe band [-5, 10]
BASELINE_ROOM = 21.0
MAX_POWER_KW = 9.0
CADENCE_H = 0.5
GAINS = 0.3          # ThermalParameters default internal_gains


def build_plant(derived: dict) -> ThermalParameters:
    return ThermalParameters(
        heat_loss_coefficient=float(derived["house_heat_loss_coefficient"]),
        house_heat_loss_scale=1.0,
        room_thermal_mass=float(derived["house_thermal_mass"]),
        internal_gains=GAINS,
        slab_thermal_mass=float(derived["slab_thermal_mass"]),
        slab_heat_transfer=float(derived["slab_heat_transfer"]),
        two_zone_enabled=False,
        wind_sensitivity=0.0,
    )


def make_samples(sid: sysid.SystemIdentification, params: ThermalParameters):
    """Roll the production plant through the sysid protocol; record room temps.

    Heat is injected at the hydronic mix (external_heat_kw), the same thermal
    quantity ``identify()``'s regressor calls ``power_kw``.
    """
    cfg = sid.config
    plant = ThermalModel(params)
    ua = params.heat_loss_coefficient * params.house_heat_loss_scale
    cap = params.room_thermal_mass
    gains = params.internal_gains
    k_s = params.slab_heat_transfer
    cop = plant.compute_cop(OUTDOOR)

    sized = sid._size_step_power(
        MAX_POWER_KW, cop, BASELINE_ROOM, OUTDOOR, ua, cap, gains,
        params.slab_thermal_mass, params.slab_heat_transfer,
    )
    step_elec = sized if sized is not None else MAX_POWER_KW * 0.3
    q = max(step_elec * cop, 0.0)   # thermal kW injected during STEP

    slab0 = BASELINE_ROOM + (ua * (BASELINE_ROOM - OUTDOOR) - gains) / max(k_s, 1e-9)
    state = ThermalState(
        room_temperature=BASELINE_ROOM,
        slab_temperature=slab0,
        outdoor_temperature=OUTDOOR,
    )
    samples = []
    now0 = 0.0
    t_end = cfg.settle_hours + cfg.step_hours + cfg.relax_hours
    t = 0.0
    while t < t_end - 1e-9:
        if t < cfg.settle_hours:
            phase = sysid.PHASE_SETTLING
        elif t < cfg.settle_hours + cfg.step_hours:
            phase = sysid.PHASE_STEP
        else:
            phase = sysid.PHASE_RELAX
        interval_power = q if phase == sysid.PHASE_STEP else 0.0
        samples.append(
            sysid.SysIdSample(
                when=__import__("datetime").datetime(2026, 1, 1)
                + __import__("datetime").timedelta(hours=t),
                room_temp=state.room_temperature,
                outdoor_temp=OUTDOOR,
                power_kw=interval_power,
                phase=phase,
            )
        )
        # advance one cadence with the interval's injected heat
        state = plant.simulate_step(
            state,
            electrical_power=0.0,
            outdoor_temp=OUTDOOR,
            dt_hours=CADENCE_H,
            external_heat_kw=interval_power,
        )
        t += CADENCE_H
    return samples, q, step_elec


def main() -> int:
    which = os.environ.get("D7_PERTURB", "")
    print(f"RESULT thread_factor=1.0 ratio")
    for name, preset in PRESETS.items():
        derived = P.derive(preset)
        params = build_plant(derived)
        # perturbation: D7_PERTURB=shrink_slab sets slab_heat_transfer to a
        # fast value (a plant the identifiability gate admits); default is the
        # shipped preset.
        if which == "fast_slab" and name == "typical_slab":
            params = build_plant({**derived, "slab_heat_transfer": 5.0})
        ua_true = params.heat_loss_coefficient * params.house_heat_loss_scale
        sid = sysid.SystemIdentification(sysid.SysIdConfig())
        samples, q, step_elec = make_samples(sid, params)

        # one-state production fit
        sid1 = sysid.SystemIdentification(sysid.SysIdConfig())
        sid1.samples = list(samples)
        r1 = sid1.identify()

        # two-state production fit, plant declared
        sid2 = sysid.SystemIdentification(sysid.SysIdConfig())
        sid2.samples = list(samples)
        sid2._slab_pair = (
            float(params.slab_thermal_mass), float(params.slab_heat_transfer)
        )
        sid2._slab_prior = (ua_true, float(params.room_thermal_mass))
        r2 = sid2.identify_slab()

        identifiable, why = sysid.slab_mode_identifiability(params, sid2.config)

        def bias(r):
            if not r.completed or r.heat_loss_kw_per_c is None:
                return None
            return 100.0 * (r.heat_loss_kw_per_c - ua_true) / ua_true

        b1, b2 = bias(r1), bias(r2)
        print(f"PRESET {name} ua_true={ua_true:.5f} q_thermal={q:.3f} "
              f"step_elec={step_elec:.3f} samples={len(samples)}")
        print(f"RESULT {name}_one_state_bias_pct="
              f"{'NA' if b1 is None else f'{b1:+.2f}'} pct")
        print(f"RESULT {name}_one_state_completed={r1.completed}")
        print(f"RESULT {name}_one_state_confidence={r1.confidence:.3f} ratio")
        print(f"RESULT {name}_one_state_reason={r1.reason!r}")
        print(f"RESULT {name}_two_state_bias_pct="
              f"{'NA' if b2 is None else f'{b2:+.2f}'} pct")
        print(f"RESULT {name}_two_state_completed={r2.completed}")
        print(f"RESULT {name}_two_state_confidence={r2.confidence:.3f} ratio")
        print(f"RESULT {name}_two_state_reason={r2.reason!r}")
        print(f"RESULT {name}_identifiable={identifiable}")
        adopted1 = bool(
            r1.completed and r1.confidence >= 0.3 and identifiable
        )
        print(f"RESULT {name}_one_state_adopted={adopted1}")
    print(f"RESULT load1=0.0 count")
    print(f"RESULT swapins=0 count")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
