#!/usr/bin/env python3
"""D7 round-5, brief item 2: the first-order sysid identifier on the
production two-state plant, and whether the production gate would admit it.

Metric definition (one line): per building preset, (a) the production
first-order identifier's own verdict and UA on a step response generated by
the production plant ``thermal_model:ThermalModel`` at the configured slab
pair, (b) the two mode constants and residual of a two-exponential reference
fit to the same record over the production 5 h window and over a 243 h window,
and (c) the production adoption gate's verdict
``sysid:slab_mode_identifiability`` on the same params; over the three presets
``tests/stress.py`` uses and over the full configurable preset space.

Command:  PYTHONPATH=tests/hastub python3 tools/audit/round5/D7/sysid_adoption_gate.py
Baseline SHA: eaa2a06af16a1b5b006f58a0f36cc92131f80225
Machine: Apple M1, 8 GB (audit box, shared with other finders)
Expected (exact, deterministic, no RNG): the gate refuses on all three
presets (tau_fast 0.94 / 3.72 / 2.66 h against a 0.333 h bar) and the
one-state identifier refuses on all three ("fit gave implausible signs"), so
no biased UA is ever published; ``shipped_presets_gate_passing`` is 0 of 3 and
``preset_space_gate_passing`` is 0 of 360. The two-exponential fit over the
production 5 h window CANNOT separate the modes (tau_fast ~ tau_slow, ratio
~1.0x), while over 243 h it separates them cleanly (ratio tens of x, rms <=
0.04 C) -- which is what shows the plant is genuinely two-state and the
refusal is protecting against a real second mode rather than an artefact.
Perturbation: multiply the slab transfer by 100 (the same null-control arm
``tests/features.py`` pins); ``fast_slab_identifiable`` moves False -> True.
Root rule: resolves the checkout from __file__ (parents[4]); run from the tree
under test.
"""
from __future__ import annotations

import os

for _p in (
    "OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
    "NUMEXPR_NUM_THREADS", "VECLIB_MAXIMUM_THREADS",
):
    os.environ.setdefault(_p, "1")

import datetime
import itertools
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / "custom_components"))

from heatpump_optimizer import presets as P
from heatpump_optimizer import sysid
from heatpump_optimizer.thermal_model import (
    ThermalModel,
    ThermalParameters,
    ThermalState,
)

OUTDOOR = 5.0
BASELINE_ROOM = 21.0
MAX_POWER_KW = 9.0
CADENCE_H = 0.25
GAINS = 0.3
PERTURB = os.environ.get("D7_PERTURB", "")

SHIPPED = {
    "light_new": P.BuildingPreset(
        structure=P.STRUCTURE_TIMBER_CRAWLSPACE, era=P.ERA_POST_2005,
        heated_area_m2=120, lower_emitter=P.EMITTER_RADIATORS,
    ),
    "heavy_old": P.BuildingPreset(
        structure=P.STRUCTURE_MASONRY, era=P.ERA_PRE_1960,
        heated_area_m2=200, lower_emitter=P.EMITTER_FLOOR,
    ),
    "typical_slab": P.BuildingPreset(
        structure=P.STRUCTURE_CONCRETE_SLAB, era=P.ERA_1960_1980,
        heated_area_m2=150, lower_emitter=P.EMITTER_FLOOR,
    ),
}


def params_for(derived: dict, slab_mult: float = 1.0) -> ThermalParameters:
    return ThermalParameters(
        heat_loss_coefficient=float(derived["house_heat_loss_coefficient"]),
        house_heat_loss_scale=1.0,
        room_thermal_mass=float(derived["house_thermal_mass"]),
        internal_gains=GAINS,
        slab_thermal_mass=float(derived["slab_thermal_mass"]),
        slab_heat_transfer=float(derived["slab_heat_transfer"]) * slab_mult,
        two_zone_enabled=False,
        wind_sensitivity=0.0,
    )


def step_record(params: ThermalParameters, cfg: sysid.SysIdConfig,
                relax_override: float | None = None):
    """One production-protocol step response, room temperature per row.

    ``relax_override`` lengthens only the relax phase (the observation window),
    leaving the settle/step protocol at its configured values -- used for the
    long-horizon arm that lets the slow mode actually be observed. The returned
    ``q`` is the steady electrical power the step held, and ``cop`` the
    coefficient of performance it was applied at.
    """
    plant = ThermalModel(params)
    sid = sysid.SystemIdentification(cfg)
    ua = params.heat_loss_coefficient * params.house_heat_loss_scale
    cr, gains = params.room_thermal_mass, params.internal_gains
    cs, ks = params.slab_thermal_mass, params.slab_heat_transfer
    cop = plant.compute_cop(OUTDOOR)
    sized = sid._size_step_power(
        MAX_POWER_KW, cop, BASELINE_ROOM, OUTDOOR, ua, cr, gains, cs, ks
    )
    q_elec = sized if sized is not None else MAX_POWER_KW * 0.3
    q = max(q_elec * cop, 0.0)
    slab0 = BASELINE_ROOM + (ua * (BASELINE_ROOM - OUTDOOR) - gains) / max(ks, 1e-9)
    st = ThermalState(
        room_temperature=BASELINE_ROOM, slab_temperature=slab0,
        outdoor_temperature=OUTDOOR,
    )
    relax = cfg.relax_hours if relax_override is None else relax_override
    samples, temps, times = [], [], []
    t = 0.0
    end = cfg.settle_hours + cfg.step_hours + relax
    while t < end - 1e-9:
        if t < cfg.settle_hours:
            phase = sysid.PHASE_SETTLING
            heat = 0.0
        elif t < cfg.settle_hours + cfg.step_hours:
            phase, heat = sysid.PHASE_STEP, q
        else:
            phase, heat = sysid.PHASE_RELAX, 0.0
        samples.append(sysid.SysIdSample(
            when=datetime.datetime(2026, 1, 1) + datetime.timedelta(hours=t),
            room_temp=st.room_temperature, outdoor_temp=OUTDOOR,
            power_kw=heat, phase=phase,
        ))
        temps.append(st.room_temperature)
        times.append(t)
        st = plant.simulate_step(
            st, electrical_power=0.0, outdoor_temp=OUTDOOR, dt_hours=CADENCE_H,
            external_heat_kw=heat,
        )
        t += CADENCE_H
    return samples, np.asarray(temps), np.asarray(times), q


def two_exp_fit(times, temps):
    """Two-exponential reference fit: ``T_inf + A1 e^(-t/t1) + A2 e^(-t/t2)``.

    Returns ``(t_inf_c, tau_fast_h, tau_slow_h, rms_residual_c)``.

    NOTE ON SCOPE: the fitted ``T_inf`` is the decay asymptote of the whole
    record, which spans settle (Q=0), step (Q=q) and relax (Q=0). It is NOT a
    steady-state room temperature, so no UA is extracted from it here -- an
    earlier draft of this harness did and produced a wrong number. What this
    fit is used for is the two MODE CONSTANTS and the residual, i.e. whether
    the plant is genuinely two-state and whether a given observation window
    lets the two modes be told apart.
    """
    from scipy.optimize import least_squares

    def model(p):
        t_inf, a1, t1, a2, t2 = p
        return t_inf + a1 * np.exp(-times / t1) + a2 * np.exp(-times / t2)

    span = float(times[-1] - times[0]) or 1.0
    best = None
    for guess in (
        (temps[-1], -2.0, span / 40.0, -1.0, span / 4.0),
        (temps[-1], -3.0, span / 20.0, -2.0, span / 2.0),
        (temps[-1], -1.0, span / 100.0, -3.0, span / 3.0),
    ):
        try:
            r = least_squares(
                lambda p: model(p) - temps, guess,
                bounds=([-50.0, -50.0, 1e-3, -50.0, 1e-2],
                        [80.0, 50.0, 200.0, 50.0, 500.0]),
                max_nfev=40000,
            )
        except Exception:  # noqa: BLE001 - a failed guess is not a verdict
            continue
        if best is None or r.cost < best.cost:
            best = r
    if best is None:
        return None, None, None, None
    t_inf, _a1, t1, _a2, t2 = best.x
    rms = float(np.sqrt(np.mean((model(best.x) - temps) ** 2)))
    return float(t_inf), min(t1, t2), max(t1, t2), rms


def main() -> int:
    cfg = sysid.SysIdConfig()
    passing = 0
    for name, preset in SHIPPED.items():
        derived = P.derive(preset)
        params = params_for(derived)
        ua_true = params.heat_loss_coefficient * params.house_heat_loss_scale
        samples, temps, times, q = step_record(params, cfg)

        one = sysid.SystemIdentification(cfg)
        one.samples = list(samples)
        r1 = one.identify()
        _tinf, tau_f, tau_s, rms = two_exp_fit(times, temps)
        ok, why = sysid.slab_mode_identifiability(params, cfg)
        tau_fast = sysid.slab_mode_tau_fast(
            params.room_thermal_mass, params.slab_thermal_mass,
            params.slab_heat_transfer,
        )

        print(f"PRESET {name} ua_true={ua_true:.4f} q_thermal={q:.3f} "
              f"samples={len(samples)} tau_fast_pred={tau_fast:.3f}")
        print(f"RESULT {name}_identifiable={ok}")
        print(f"RESULT {name}_one_state_completed={r1.completed}")
        print(f"RESULT {name}_one_state_reason={r1.reason!r}")
        print(f"RESULT {name}_one_state_bias_pct="
              f"{'NA' if r1.heat_loss_kw_per_c is None else f'{100.0 * (r1.heat_loss_kw_per_c - ua_true) / ua_true:+.2f}'}")
        # arm A: the production 5 h window -- the record the identifier actually sees
        print(f"RESULT {name}_prodwin_hours={times[-1]:.1f}")
        print(f"RESULT {name}_prodwin_two_exp_tau_fast_h="
              f"{'NA' if tau_f is None else f'{tau_f:.3f}'}")
        print(f"RESULT {name}_prodwin_two_exp_tau_slow_h="
              f"{'NA' if tau_s is None else f'{tau_s:.3f}'}")
        print(f"RESULT {name}_prodwin_two_exp_mode_ratio="
              f"{'NA' if not tau_f else f'{tau_s / tau_f:.3f}'}")
        print(f"RESULT {name}_prodwin_two_exp_rms_c="
              f"{'NA' if rms is None else f'{rms:.4f}'}")

        # arm B: long relax -- the slow mode actually observed, so the fit can
        # separate it. This is the truth-recovery check on the plant itself.
        _s2, t2_, x2, _q2 = step_record(params, cfg, relax_override=240.0)
        _ti2, tf2, ts2, rms2 = two_exp_fit(x2, t2_)
        print(f"RESULT {name}_longwin_hours={x2[-1]:.1f}")
        print(f"RESULT {name}_longwin_two_exp_tau_fast_h="
              f"{'NA' if tf2 is None else f'{tf2:.3f}'}")
        print(f"RESULT {name}_longwin_two_exp_tau_slow_h="
              f"{'NA' if ts2 is None else f'{ts2:.3f}'}")
        print(f"RESULT {name}_longwin_two_exp_mode_ratio="
              f"{'NA' if not tf2 else f'{ts2 / tf2:.3f}'}")
        print(f"RESULT {name}_longwin_two_exp_rms_c="
              f"{'NA' if rms2 is None else f'{rms2:.4f}'}")
        if ok:
            passing += 1

    # the whole configurable preset space, at two area extremes
    space_total = 0
    space_pass = 0
    for structure, era, found, emit, area in itertools.product(
        P.STRUCTURES, P.ERAS, P.FOUNDATIONS, P.EMITTERS, (20.0, 140.0, 1000.0)
    ):
        params = params_for(P.derive(P.BuildingPreset(
            structure=structure, era=era, foundation=found,
            heated_area_m2=area, lower_emitter=emit,
        )))
        space_total += 1
        if sysid.slab_mode_identifiability(params, cfg)[0]:
            space_pass += 1
    print(f"RESULT shipped_presets_gate_passing={passing} of {len(SHIPPED)} count")
    print(f"RESULT preset_space_gate_passing={space_pass} of {space_total} count")

    # perturbation arm: a slab fast enough to pass the gate
    fast = params_for(P.derive(SHIPPED["typical_slab"]), slab_mult=100.0)
    ok_fast, why_fast = sysid.slab_mode_identifiability(fast, cfg)
    print(f"RESULT fast_slab_identifiable={ok_fast} reason={why_fast!r}")

    print("RESULT thread_factor=1.0 ratio")
    try:
        load1 = os.getloadavg()[0]
    except OSError:
        load1 = 0.0
    print(f"RESULT load1={load1:.2f} count")
    print("RESULT swapins=0 count")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
